mdc-theme/src/main/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeFromMdcTheme.kt

Currently the theme is read on every recomposition, which is obviously very wasteful. Reading from a theme is very slow so we should cache the values when the theme hasn't actually changed.
`Theme` does not currently implement normal object equality, so we need to use the internal and hidden `getKey()` method to use as an equality key.
/cc @alanv

Avoid reading the MDC theme on every composition

---

mdc-theme/build.gradle
mdc-theme/src/main/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeFromMdcTheme.kt
sample/build.gradle
sample/src/main/AndroidManifest.xml
sample/src/main/java/dev/chrisbanes/accompanist/sample/MainActivity.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/mdc/MdcSampleActivity.kt
sample/src/main/res/values/colors.xml
sample/src/main/res/values/shape.xml
sample/src/main/res/values/themes.xml

Also fixed an issue where we were not reading `[android:]fontFamily="sans-serif-light"` (and other named) font families.

Add MDC sample

---

coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilSampleActivity.kt

Allows displaying custom content while the request is ongoing. The sample displays a `CircularProgressIndicator`.

Add `loading` slot to CoilImage

---

mdc-theme/src/main/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeFromMdcTheme.kt

Currently we use a reflective framework call to `Theme.getKey()` to use a key for remembering the result. That doesn't work on places where the SDK greylist is in operation, and we currently log every time on those API levels.
This commit fixes that by going back to a traditional reflective call setup, and removing all logging.

Fix logging in MaterialThemeFromMdcTheme

---

sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilSampleActivity.kt

Some of the images on `loremflickr.com` were not appropriate for a public sample. `picsum.images` contains a curated list of images which are appropriate.

Use picsum.images for sample app

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
mdc-theme/src/androidTest/AndroidManifest.xml
mdc-theme/src/androidTest/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeTest.kt
mdc-theme/src/androidTest/java/dev/chrisbanes/accompanist/mdctheme/NotMdcActivity.kt
mdc-theme/src/androidTest/res/values/themes.xml
mdc-theme/src/main/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeFromMdcTheme.kt
mdc-theme/src/main/res/values/theme_attrs.xml

This improves the check that requires the context is using a `Theme.MaterialComponents.*` theme. MDC introduced a particular attr for this: [`isMaterialTheme`](https://github.com/material-components/material-components-android/blob/e2eec4aca1795c2795f52098e391c85ccc95a1a4/lib/java/com/google/android/material/color/res/values/attrs.xml#L55).
I considered using [`ThemeEnforcement#obtainStyledAttributes`](https://github.com/material-components/material-components-android/blob/master/lib/java/com/google/android/material/internal/ThemeEnforcement.java#L67) (which makes use of this attr) but it's quite verbose and is currently restricted to the library group.
A basic test for this was added.
Note: AGP was also updated to 4.2.0-alpha02.

Improve MDC theme assertion

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Modifier.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/RequestActor.kt

`WithConstraints` is not suitable for how we're using it, so we're moving to `Modifier.onSizeChanged()` (which is based on `Modifier.onPositioned`). This required some changes to how CoilImage is implemented. While here, I also migrated us to the new `launchInComposition()` to launch our Coil request.

Move away from using `WithConstraints`

---

coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/Assertions.kt
coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
coil/src/androidTest/res/drawable-nodpi/blue_rectangle.xml
coil/src/androidTest/res/drawable-nodpi/red_rectangle.xml
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt

We were using a `state` for storing the previous load result, which meant that we would use the same result, regardless of whether the data/request changes. Fixed by using `stateFor(data)` instead.
While writing the test, I also found that loading drawables with no intrinsic size (`<shape>`s, etc) would crash while being drawn to a bitmap (because they have 0px intrinsic width/height). Fixed by passing through the request size as a fallback.

Fix CoilImage not refreshing if data changes

---

build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/build.gradle
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
gradle.properties
mdc-theme/build.gradle
mdc-theme/src/main/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeFromMdcTheme.kt
sample/build.gradle

Required some changes to `generateMaterialThemeFromMdcTheme()`. Calling composable functions is no longer allowed within `remember {}` calls, so I converted `generateMaterialThemeFromMdcTheme()` to be non-composable. There was no real need for it to be composable, other than convenient access to ambients.

Update to Compose SNAPSHOT #6658922

---

coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt

Currently we invoke Coil on every size change, which is correct but a lot of wasted work most of the time. We no longer re-fetch on every size change. If developers want to customize this, they can use the new `shouldRefetchOnSizeChange` lambda parameter to allow re-fetching as they see fit.

Stop refetching on every size change by default

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt

Kotlin 1.4.0 is stable, updating to that version.

Upgrade to Kotlin 1.4.0

---

build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt

Also fixed the logic for detecting whether a custom `SizeResolver` has been set. Thanks for the hint @colinrtwhite!

Update to Coil v1.0.0-rc1

---

.github/workflows/build.yml

Less folders should help improve the restore/save cache times

Improve Gradle caching in Actions

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/api/coil.api
coil/build.gradle
coil/src/androidTest/AndroidManifest.xml
coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTestApplication.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/RequestActor.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt

As we're on a roll of API changes, here's one final change:
- `SuccessResult` and `ErrorResult` have now been expanded in the sealed `CoilImageState`, which now contains: `Success`, `Error`, `Loading` & `Empty`
- The recent `CoilImage` with the `image` composable has been expanded and made more flexible:
``` kotlin
CoilImage(
data = "https://www.image.url",
) { state ->
when (state) {
is CoilImageState.Success -> // TODO
is CoilImageState.Error -> // TODO
CoilImageState.Loading -> // TODO
CoilImageState.Empty -> // TODO
}
}
```
The more opinionated (and easier to use) version which hosts content slots still exists, allowing:
``` kotlin
CoilImage(
data = "https://www.image.url",
fadeIn = true,
loading = { /* content to show while loading */ },
error = { /* content to show when an error has …
```

More API changes

---

build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt

Turned off `-Xjvm-default=all` as per Coil [release notes](https://github.com/coil-kt/coil/releases/tag/1.0.0-rc3), and started using new `imageLoader` extension property.
/cc @colinrtwhite

Update to Coil 1.0.0-rc3

---

picasso/src/main/java/dev/chrisbanes/accompanist/picasso/Picasso.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/picasso/PicassoBasicSample.kt

We now use `centerInside()` which maintains aspect ratio, but could lead to images being scaled smaller than the composable.
Closes #118

Fix PicassoImage not maintaining aspect ratio when resizing

---

coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
picasso/build.gradle
picasso/src/androidTest/java/dev/chrisbanes/accompanist/picasso/PicassoTest.kt
picasso/src/androidTest/java/dev/chrisbanes/accompanist/picasso/SingleThreadPauseableExecutor.kt

We now follow the same pattern across the libraries, of injecting a pauseable 'runner' (executor, dispatcher) and then resuming once we're ready.
Closes #105

De-flake `loading_slot` tests

---

coil/README.md
coil/api/coil.api
coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt

Allows setting of a default `ImageLoader` across all `CoilImage`s.

Add AmbientImageLoader for Coil

---

glide/README.md
glide/api/glide.api
glide/src/androidTest/java/dev/chrisbanes/accompanist/glide/GlideTest.kt
glide/src/androidTest/java/dev/chrisbanes/accompanist/glide/SimpleRequestListener.kt
glide/src/main/java/dev/chrisbanes/accompanist/glide/GlideImage.kt

Similar to what has been added to Coil + Picasso

Add AmbientRequestManager for GlideImage

---

.github/workflows/build.yml

We now manually run assemble & dokka before `uploadArchives`. If we only run `uploadArchives`, the assemble and dokka tasks are run interleaved on each module, which can cause connection timeouts to Sonatype (since we need to wait for assemble+dokka to finish).
By front-loading the assemble+dokka tasks, the upload itself is much quicker, and less likely to timeout.
Raised: https://github.com/vanniktech/gradle-maven-publish-plugin/issues/170

Make upload to Sonatype less flaky

---

coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
glide/src/androidTest/java/dev/chrisbanes/accompanist/glide/GlideTest.kt
imageloading-core/src/main/java/dev/chrisbanes/accompanist/imageloading/ImageLoad.kt
picasso/src/androidTest/java/dev/chrisbanes/accompanist/picasso/PicassoTest.kt

We now start from the Loading state, since we switch instantly to Loading in 99% of cases. This means we no longer display the Empty state as start before switching to Loading one composition later.
We now treat Empty as a terminal/result state.
Closes #141

[Image Loading] Skip initial `Empty` state

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
insets/api/insets.api
insets/src/main/java/dev/chrisbanes/accompanist/insets/Insets.kt
sample/build.gradle
sample/src/main/AndroidManifest.xml
sample/src/main/java/dev/chrisbanes/accompanist/sample/insets/InsetsFragmentSample.kt
sample/src/main/res/values/strings.xml

This enables fragments to manage their own `WindowInsets` and setup the necessary listeners earlier than `ProvideWindowInsets`. See the related issue for more information on why this is needed.
Fixes #155

Add ViewWindowInsetObserver

---

.idea/codeStyles/Project.xml
insets/api/insets.api
insets/src/main/java/dev/chrisbanes/accompanist/insets/Insets.kt
insets/src/main/java/dev/chrisbanes/accompanist/insets/Padding.kt
sample/src/main/AndroidManifest.xml
sample/src/main/java/dev/chrisbanes/accompanist/sample/insets/EdgeToEdgeLazyColumn.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/insets/ImeAnimationSample.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/insets/ListItems.kt
sample/src/main/res/values/strings.xml

This brings initial support for `WindowInsetsAnimation` to Accompanist Insets. The API is marked as experimental, since it's not final and will likely be refined.

Keyboard (IME) animation support

---

coil/src/androidTest/java/dev/chrisbanes/accompanist/coil/CoilTest.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
glide/src/androidTest/java/dev/chrisbanes/accompanist/glide/GlideTest.kt
glide/src/main/java/dev/chrisbanes/accompanist/glide/GlideImage.kt
imageloading-testutils/src/main/res/drawable/ic_android_black_24dp.xml
picasso/src/androidTest/java/dev/chrisbanes/accompanist/picasso/PicassoTest.kt
picasso/src/main/java/dev/chrisbanes/accompanist/picasso/Picasso.kt

GlideImage, CoilImage and PicassoImage currently all accept an `Any` param for data. There have been examples of developers passing in things like Drawables, ImageBitmaps, and others, which are not supported. To aid developers, we now throw an exception when any `Drawable`, `ImageBitmap`, `ImageVector` or `Painter` is passed in.

[Image] Throw exception if incorrect data type is passed in

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt

Allows us to remove our workaround for `remember()`.
Required update to Kotlin 1.4.21.

Update to Compose SNAPSHOT 7033025

---

.github/workflows/build.yml

Our workaround isn't quite working now, so instead split out the commands to ensure that the build is ran before deploy.

Build docs before deploy

---

imageloading-core/api/imageloading-core.api
imageloading-core/src/main/java/dev/chrisbanes/accompanist/imageloading/MaterialLoadingImage.kt

Required API change, since the `clock` param is no longer necessary.
Fixes #187

Update to the Transition v2 APIs

---

glide/src/main/java/dev/chrisbanes/accompanist/glide/GlideImage.kt
imageloading-core/src/main/java/dev/chrisbanes/accompanist/imageloading/ImageLoad.kt

Our custom RequestActor was working fine, but using the built-in side effect means less code for us to maintain.

Migrate to using produceState

---

sample/src/main/java/dev/chrisbanes/accompanist/sample/insets/EdgeToEdgeLazyColumn.kt

The sample for `InsetAwareTopAppBar` currently doesn't take into account the navigation bar in landscape mode. When in landscape, either the `navigationIcon` or an `action` are overlapped by the Navigation bar. This PR fixes this so that all icons are visible in portrait as well as landscape mode.
Ideally, I think this might be better off applied in something like an `InsetAwareScaffold` since the `bodyContent` will also need to have this modifier.

Fix actions or navigationIcon covered by navigation bar in landscape

---

coil/README.md

Add contentDescription argument to CoilImage declarations, as this is a required argument when using the composable.
I'm not sure if this was intentionally left out to keep things simple, but I feel having this here removes the need for users to question why they are seeing errors after copying any samples from here. Feel free to disregard this if it was intentional :)

Add contentDescription argument to readme

---

imageloading-core/src/main/java/dev/chrisbanes/accompanist/imageloading/MaterialLoadingImage.kt

I'm not a ColorMatrix expert but it seems to me the correct way to set brightness is to use 5th columns of color matrix - not 4th.
Here's another implementation of Material image loading that uses the proposed way of setting brightness http://blog.neteril.org/blog/2014/11/23/android-material-image-loading/
Feel free to close this if I'm wrong.

Fixed ColorMatrix brightness adjustment

---

imageloading-core/src/main/java/dev/chrisbanes/accompanist/imageloading/ImageLoad.kt

Currently our logic will treat a `CancellationException` as an error result, rather than the request being
cancelled. This PR updates our logic to re-throw `CancellationException`s.
Fixes #217

Handle CancellationException in produceState

---

appcompat-theme/src/androidTest/java/dev/chrisbanes/accompanist/appcompattheme/AppCompatThemeTest.kt
appcompat-theme/src/main/java/dev/chrisbanes/accompanist/appcompattheme/AppCompatTheme.kt

We update the `LocalContentColor` to match our `onBackground`. This allows the default content color to be more appropriate to the theme background.
Fixes #222

[AppCompat] Set LocalContentColor

---

insets/api/insets.api
insets/src/main/java/com/google/accompanist/insets/Insets.kt

Make coerceEachDimensionAtLeast() public API

---

insets/api/insets.api
insets/src/androidTest/java/com/google/accompanist/insets/InsetsAssertions.kt
insets/src/main/java/com/google/accompanist/insets/Insets.kt
insets/src/main/java/com/google/accompanist/insets/Padding.kt
insets/src/main/java/com/google/accompanist/insets/Size.kt

This PRs refactors the `Insets` class so it now stores:
- Layout insets
- Animated insets
- Animated progress fraction
The types of properties have changed slightly (so technically API breaking), but the actual typical usage is exactly the same: `LocalWindowInsets.statusBars.top`.
Fixes #227

Expose progress of animated insets

---

insets/src/main/java/com/google/accompanist/insets/Insets.kt

Currently LocalWindowInsets will throw an exception if it is referenced without being provided a value. This is a problem when using layouts in previews though, so we instead provide our default empty value there

Provide default empty value to LocalWindowInsets

---

pager/api/pager.api
pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
sample/src/main/java/com/google/accompanist/sample/pager/DocsSamples.kt

Allow apps to collect any current page changes via a `Flow`. Typical usage looks like the following:
``` kotlin
val pagerState = rememberPagerState(pageCount = 10)
LaunchedEffect(pagerState) {
// Collect from the PageState's pageChanges, which emits when the
// current page has changed
pagerState.pageChanges.collect { page ->
AnalyticsService.sendPageSelectedEvent(page)
}
}
```

[Pager] Add PagerState.pageChanges

---

pager/api/pager.api
pager/src/main/java/com/google/accompanist/pager/Pager.kt

This commit adds a parameter to the Pager composable to disable scrolling by hand. If disabled, PagerState.animateScrollToPage() can be used to programmatically switch to a different page.

Pager parameter to disable scrolling by hand

---

pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/TestUtils.kt

Due to async coroutines which sometimes wouldn't complete before the test finished. Fixed by using `TestCoroutineScope` and `suspendTest()` from Turbine.

Fix async flakiness in pageChangesSample test

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt

I've been using the paging indicator library and noticed that the width was being used for the page indicator containers, but not the active indicator.
I updated it to use the passed in width for the active indicator, instead of the height.

[Pager] Use passed in width for active indicator

---

pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerInfiniteHeightTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/VerticalPagerInfiniteHeightTest.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerTabsSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerWithIndicatorSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/VerticalPagerBasicSample.kt

Current Pager blindly uses the maxHeight/Width constraints, which breaks down when the pager is given infinite max constraints.
This PR updates our measure/layout to wrap the page content by default, and then coerces that by the min constraints.
Fixes #300

[Pager] Handle infinite constraints

---

pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/VerticalPagerTest.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt

Pager was using `placeRelative()` which only honours the layout direction and not the `reverseLayout` value.
Fixes #297

[Pager] Fix reverseLayout = true

---

docs/pager.md
pager-indicators/api/pager-indicators.api
pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt
pager/api/pager.api
pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
sample/src/main/java/com/google/accompanist/sample/pager/DocsSamples.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerTabsSample.kt

Reading the selected page is a common use for pagers, especially when used with things like Tabs. This PR clarifies what currentPage and currentPageOffset to mean the 'selected page', and thus only get updated after a scroll has completed.
This allows us to tidy up the Tab offset modifier and make it a provided function in the library.
Internally, we've now separated the 'selected page' from the internal 'layout page' (and offset), which allows us to set the selected page only once a scroll has finished.
Fixes #280

[Pager] Update currentPage to act as the selected page

---

pager/api/pager.api
pager/src/main/java/com/google/accompanist/pager/PagerState.kt

This change exposes the animationSpec parameter from `PagerState.animateToPage()` (which is private) to `PagerState.animateScrollToPage()` so that the animation can be changed as needed.

Expose animation spec in animateScrollToPage()

---

systemuicontroller/api/systemuicontroller.api
systemuicontroller/src/androidTest/java/com/google/accompanist/systemuicontroller/SystemUiControllerTest.kt
systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt

Fixes #317.
I'm not sure about the naming of the APIs. 
Also, is there is a better way to test this on different system gesture modes?

[SystemUiController] Add Window.isNavigationBarContrastEnforced APIs

---

docs/systemuicontroller.md
sample/src/main/java/com/google/accompanist/sample/insets/EdgeToEdgeLazyColumn.kt
sample/src/main/java/com/google/accompanist/sample/insets/ImeAnimationSample.kt
sample/src/main/java/com/google/accompanist/sample/insets/InsetsBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/insets/InsetsFragmentSample.kt
sample/src/main/java/com/google/accompanist/sample/systemuicontroller/DocsSamples.kt
systemuicontroller/api/systemuicontroller.api
systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt

- Deprecated `Local SystemUiController`. There's no real need for a composition local to store the `SystemUiController`. They're infrequently enough that simply using `rememberSystemUiController()` as necessary works.
- Hid `AndroidSystemUiController` class.
- Renamed `rememberAndroidSystemUiController()` to `rememberSystemUiController()`

[SystemUiController] API fixes

---

.github/workflows/publish-docs.yml
generate_docs.sh

Highlighted by #331. 
The [docs push](https://github.com/google/accompanist/actions/runs/7268044290) for v0.7.1 reported as successful, but actually failed:
```
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during code generation
File being compiled: /home/runner/work/accompanist/accompanist/imageloading-core/src/main/java/com/google/accompanist/imageloading/AndroidDrawablePainter.kt
The root cause java.lang.OutOfMemoryError was thrown at: unknown
```

Fix docs build actions

---

pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt

We were missing a `snapToNearestPage()`
Fixes #337

Update currentPager after calling scrollToPage()

---

.github/workflows/build.yml
pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/TestUtils.kt

We're now running on all API levels 21-30 to see what works, and what doesn't.

Update test runs on CI

---

swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt

Previously we allowed dragging of the indicator when it was
'refreshing'. This no longer works perfectly when the recent
migration the offset logic to the SwipeRefreshIndicator.
This PR removes this feature for now, until we can make it work
well with the new indicator.

[SwipeRefresh] Simplify drag handling for now

---

swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefreshIndicator.kt

Previously we used a default of 4.dp, which is looking slightly too faint. 6.dp feels like a good value, both in light and dark themes.

[SwipeRefresh] Increase SwipeRefreshIndicator elevation

---

coil/src/androidTest/java/com/google/accompanist/coil/CoilTest.kt
glide/src/androidTest/java/com/google/accompanist/glide/GlideTest.kt
imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt

We now default the size to be -1, -1, which means that we load the full size image. If a draw happens (due to us having a size), then the request size is overwritten and we load that instead.

Fix LoadPainter not fetching image with no explicit size

---

coil/src/androidTest/java/com/google/accompanist/coil/CoilIdlingResource.kt
coil/src/androidTest/java/com/google/accompanist/coil/CoilTest.kt

Works fine locally, but there must be a race condition
when running on slower machines (i.e. CI).

[Coil] Fix lazycolumn_nosize on CI

---

insets/src/main/java/com/google/accompanist/insets/Insets.kt

We were accidentally adding a new attach listener every time, which meant that the one being removed wasn't actually attached.
Fixes #364

[Insets] Fix attach state change listener not being removed

---

pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/VerticalPagerTest.kt

Using a workaround for https://issuetracker.google.com/issues/179492185

[Pager] Re-enable animateScrollToPage() test

---

sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshContentPaddingSample.kt
swiperefresh/api/current.api
swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt

We now clip the indicator to the bounds of the content, or the indicatorPadding, depending on what value is provided.
Fixes #377

[SwipeRefresh] Add clipIndicatorToPadding parameter

---

coil/src/androidTest/java/com/google/accompanist/coil/DeprecatedCoilTest.kt
coil/src/main/java/com/google/accompanist/coil/Coil.kt
coil/src/main/java/com/google/accompanist/coil/DeprecatedCoil.kt
glide/src/androidTest/java/com/google/accompanist/glide/DeprecatedGlideTest.kt
glide/src/main/java/com/google/accompanist/glide/DeprecatedGlide.kt
glide/src/main/java/com/google/accompanist/glide/Glide.kt
imageloading-core/api/current.api
imageloading-core/src/main/java/com/google/accompanist/imageloading/ImageLoadState.kt
imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt
imageloading-testutils/src/main/java/com/google/accompanist/imageloading/test/ImageAssetAssertions.kt
sample/src/main/java/com/google/accompanist/sample/coil/CoilBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/glide/GlideBasicSample.kt

`Loader` now returns a `Flow<ImageLoadState>` which allows the loader to control the entire stream, including the
'Loading' state. This allows the loading state to contain any placeholder drawables which may be set on the request.
Example:
``` kotlin
Image(
painter = rememberCoilPainter(
request = "some.url",
requestBuilder = {
placeholder(R.drawable.placeholder)
}
),
contentDescription = null,
)
```

[Image loading] Support placeholder drawables

---

pager/src/androidTest/java/com/google/accompanist/pager/PagerStateUnitTest.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt

There's no need to store the page offset as it could technically be out of bounds (example: if the state was stored during an animation).
Fixes #417

[Pager] Fix PagerState restoration

---

docs/coil.md
docs/glide.md
generate_docs.sh
mkdocs.yml

Coil should be preferred for most applications due to its usage of Kotlin Coroutines.

[Glide] Highlight Coil on Glide guide

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt
pager/api/current.api
pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/VerticalPagerTest.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerLoopSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/VerticalPagerLoopSample.kt
sample/src/main/res/values/strings.xml

Currently, the pager can only scroll within a limited range, so it can only scroll in one direction on the first or last page.
This PR provides the option to allow the pager to scroll infinitely.
Fixes: #429
https://user-images.githubusercontent.com/3405740/119264584-c714c500-bc1e-11eb-9f69-2e43d142e441.mp4
https://user-images.githubusercontent.com/3405740/119264589-cbd97900-bc1e-11eb-9a1f-9f9eb6721214.mp4

[Pager] Supports infinite loop

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt

Currently when `animateToPageSkip` is called with the target page in the left of the current page, there are some problems when calculating pages during animation, which results in some strange behavior as shown in the video (it's easier to understand if you look at the indicators).
https://user-images.githubusercontent.com/9391933/119474035-b8492200-bd86-11eb-9f64-145b1f1e85e6.mp4
This PR fixes the problem.

[Pager] Fix backward animateScrollToPage when skipping pages

---

swiperefresh/api/current.api
swiperefresh/src/main/java/com/google/accompanist/swiperefresh/Slingshot.kt
swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefreshIndicator.kt

Also fix arc `endTrim` drawing.
Before:
https://user-images.githubusercontent.com/12491712/119508190-d5262b00-bd6f-11eb-8987-482ccb11ec9b.mp4
After:
https://user-images.githubusercontent.com/12491712/119508210-d9524880-bd6f-11eb-83ea-c1c9881ddb1b.mp4
resolves #431

[SwipeRefresh] Update indicator to fade-in during drag

---

sample/src/main/java/com/google/accompanist/sample/glide/GlideLazyColumnSample.kt

This is a minor fix.
Currently in `GlideLazyColumnSample`, `rememberCoilPainter()` is used.
So I changed `rememberCoilPainter()` to `rememberGlidePainter()`.

Fix wrong Coil API usage in Glide sample

---

pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerScrollingContentTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/VerticalPagerScrollingContentTest.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerScrollingContentSample.kt
sample/src/main/res/values/strings.xml

Currently any nested unused scrolls + flings from child content is handled by the Pager. This is different to how `ViewPager[2]` behaves and is usually unwanted behavior.
This PR adds a `NestedScrollConnection` which consumes those events before the Pager gets them. It's not perfect, but it's close enough for now.
Fixes #347

[Pager] Consume post flings and scrolls from nested scrolling content

---

imageloading-core/src/main/java/com/google/accompanist/imageloading/DrawablePainter.kt

We no longer need to pre-scale the Canvas as the modifier is now responsible for scaling and positioning the canvas as appropriate.

[DrawablePainter] Stop pre-scaling the Canvas

---

appcompat-theme/build.gradle
build.gradle
coil/build.gradle
flowlayout/build.gradle
glide/build.gradle
imageloading-core/build.gradle
insets/build.gradle
pager-indicators/build.gradle
pager/build.gradle
swiperefresh/build.gradle
systemuicontroller/build.gradle

Needed to move all of the Metalava plugin configuration to the root `build.gradle`, so that we could ensure that the plugin was applied before trying to fetch the task.
Workaround for https://github.com/tylerbwong/metalava-gradle/issues/12

Check API files via `check` task

---

docs/insets.md
insets/api/current.api
insets/src/main/java/com/google/accompanist/insets/WindowInsets.kt

It is now enabled by default! We can now remove the overloads for the experimental APIs.
Fixes #461

[Insets] Animated insets support is now longer experimental 🥳

---

placeholder/README.md
placeholder/api/current.api
placeholder/gradle.properties
placeholder/src/androidTest/java/com/google/accompanist/placeholder/ImageAssertions.kt
placeholder/src/androidTest/java/com/google/accompanist/placeholder/PlaceholderAnimatedBrush.kt
placeholder/src/androidTest/java/com/google/accompanist/placeholder/PlaceholderTest.kt
placeholder/src/main/java/com/google/accompanist/placeholder/Placeholder.kt
placeholder/src/main/java/com/google/accompanist/placeholder/PlaceholderAnimatedBrush.kt

- Use `remember` with keys.
- Add more tests to validate recomposition situations.
- Add README and gradle.properties missing in #457.
Fixes #466.
| Before | After |
|---------------|--------------|
| <img width="300" src="https://user-images.githubusercontent.com/3405740/120853024-08f62180-c5b6-11eb-9aaa-5ecf914ee874.gif" /> | <img width="300" src="https://user-images.githubusercontent.com/3405740/120853014-05fb3100-c5b6-11eb-826b-c19c3c6e3d5e.gif" /> |

[Placeholder] Fix that a placeholder modifier is not changed on every recomposition

---

.github/workflows/build.yml
appcompat-theme/src/androidTest/java/com/google/accompanist/appcompattheme/DummyTests.kt
insets/src/androidTest/java/com/google/accompanist/insets/DummyTests.kt
placeholder/src/androidTest/java/com/google/accompanist/placeholder/DummyTests.kt
swiperefresh/src/androidTest/java/com/google/accompanist/swiperefresh/DummyTests.kt
swiperefresh/src/androidTest/java/com/google/accompanist/swiperefresh/SwipeRefreshTest.kt
systemuicontroller/src/androidTest/java/com/google/accompanist/systemuicontroller/DummyTests.kt

This PR now shards the instrumented tests over 3 emulator runs per API level. Each shard now takes ~20 mins to run, whereas previously each API level would take ~40-50 mins.
We have needed to add a bunch of 'dummy' tests to each module. If the resulting number of tests in a shard is 0 we hit 'No tests found' errors. The dummy tests bulk out the number of tests to reduce/stop the chance of a shard having 0 tests. See https://github.com/android/android-test/issues/973.

Start sharding tests on CI

---

.github/workflows/build.yml
.github/workflows/device-tests.yml
build.gradle
gradle/libs.versions.toml
scripts/run-device-tests.sh

We now use https://github.com/dropbox/AffectedModuleDetector to only run tests from affected modules for PRs and commits (i.e. to main).
We also now have a twice-daily workflow which runs all tests on emulators, for sanity checking purposes.
Confirmed that this works in #473

[All] Only run tests on affected modules

---

placeholder-material/api/current.api
placeholder-material/src/main/java/com/google/accompanist/placeholder/material/Placeholder.kt
placeholder/api/current.api
placeholder/src/main/java/com/google/accompanist/placeholder/Placeholder.kt

The content and placeholder is now cross-faded when the `visible` value changes. The transition can be customized via the new transition spec parameters.
https://user-images.githubusercontent.com/227486/121664312-41f33200-ca9f-11eb-84d2-62b7dde75f53.mp4

[Placeholder] Add cross-fade between content + placeholder

---

gradle/libs.versions.toml

We can't use `7443347` as there isn't a snapshot build for that build id.

Update to Compose SNAPSHOT 7443455

---

pager/api/current.api
pager/src/main/java/com/google/accompanist/pager/Clipping.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt

We've used the same approach that LazyColumn and LazyRow use.
https://android-review.googlesource.com/c/platform/frameworks/support/+/1713918
Fixes #498

[Pager] Fix clipping on the cross-axis

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerLoopSample.kt

Currently, `animateScrollToPage()` only accepts `page` in range from first to last.
So if calls `animateScrollToPage()` to scroll from the first to the last, it will move to the **right** direction.
But in infinite loop mode, it would be nice to be able to scroll even in the nearest direction.
Now allow scrolling to **pages out of bounds** in infinite loop mode.
For examples:
- If calls `animateScrollToPage(-1)`, move to the **left** direction. And the current page will be `pages.size`.
- If calls `animateScrollToPage(pages.size)`, move to the **right** direction. And the current page will be `0`.
And add `ActionRow` in loop pager sample.
Fixes #503 
https://user-images.githubusercontent.com/3405740/122672310-f1e63f00-d205-11eb-8ea2-9e6ef2e90665.mp4

[Pager] In infinite loop mode, allow scrolling to pages out of bounds

---

docs/permissions.md
permissions/src/androidTest/java/com/google/accompanist/permissions/MultipleAndSinglePermissionsTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/RequestMultiplePermissionsTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/RequestPermissionTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/test/PermissionsTestActivity.kt
sample/src/main/java/com/google/accompanist/sample/permissions/RequestMultiplePermissionsSample.kt
sample/src/main/java/com/google/accompanist/sample/permissions/RequestPermissionSample.kt

It's a bad UX to show the permission as an effect of a navigation event. When the permission is presented, the user should have enough context to grant/deny the permission.

[Permissions] Improve UX experience in samples and tests

---

README.md

Hello! First, thanks so much for your work on Accompanist – it’s been of great utility. I’d like to suggest some stylistic and linguistic tweaks to the overview section of the README. I’ve referenced the [Google developer documentation style guide](https://developers.google.com/style) and [_AP Stylebook_](https://www.apstylebook.com/) in introducing these edits. Here’s a line-by-line description:
- Line 3: _Which_ should be used for non-essential clauses, whereas _that_ should be used for essential clauses. From the _AP Stylebook_: ‘... If you can drop the clause and not lose the meaning of the sentence, use _which_; otherwise, use _that_.’ Additionally, _but_ shouldn’t be preceded by a comma here because, as per the _AP Stylebook_, commas are to be placed before a conjunction only when …

README: Copy-edit overview section

---

imageloading-core/api/current.api
imageloading-core/src/main/java/com/google/accompanist/imageloading/DrawablePainter.kt

I have a use case where I need to both render the drawable loaded by Glide and extract it's bitmap to generate a glowing effect around it. With the change in https://github.com/google/accompanist/pull/402 that replaced the `drawable` result param for a `Painter` broke our implementation and I couldn't find an alternative solution to achieve the same effect with the `Painter` and have thus opened this PR.
Thanks for the consideration!

Expose the Drawable in DrawablePainter

---

permissions/build.gradle

`libs.kotlin.metadataJvm` needs to be shipped with the `permissions-lint` module. `implementation` doesn't work with `lintPublish`, therefore, we need to build `permissions-lint` as a fat jar. Meanwhile, let's not add the lint checks.

[Permissions] Remove lint checks until a solution is found

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt

It looks like all properties need to be saved.
Fix: #545

[Pager] add offscreenLimit to PagerState Saver

---

.github/workflows/build.yml
.github/workflows/device-tests.yml

To workaround https://github.com/ReactiveCircus/android-emulator-runner/issues/160. Also removed running tests on API 28 as they seem to be causing the emulator to fail.

Pin Android Emulator back on CI

---

.github/workflows/build.yml
.github/workflows/device-tests.yml

Related: https://github.com/ReactiveCircus/android-emulator-runner/issues/168

Re-enable API 28 emulators on CI

---

insets-ui/build.gradle
insets-ui/src/main/java/com/google/accompanist/insets/ui/Scaffold.kt
insets-ui/src/sharedTest/kotlin/com/google/accompanist/insets/ScaffoldTest.kt

This PR fixes the issue that it does not currently honour the nested content padding.
Copied over the Scaffold tests from cs.android.com and tweaked as necessary to match the new behavior.

Fix Scaffold FloatingActionButton position

---

pager-indicators/build.gradle
pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt
pager-indicators/src/sharedTest/kotlin/com/google/accompanist/insets/DummyTests.kt
pager-indicators/src/sharedTest/kotlin/com/google/accompanist/insets/TabIndicatorTest.kt

Happens when the pager has 0 pages, which can happen during init.

Fix pagerTabIndicatorOffset crashing

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseHorizontalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseVerticalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

If the Pager composable is recomposed during a scroll it currently resets back to the original page. This is because the recomposition will call `rememberPagerState()`, which updates the `PagerState.pageCount` count value, which triggers a page layout update.
There's no real need to update the layout when this happens, as the updated `currentPage` will do it as necessary. Fixed by removing that call.
Fixes #585

[Pager] Fix recomposition affecting scrolling

---

navigation-animation/src/androidTest/java/com/google/accompanist/navigation/animation/AnimatedNavHostTest.kt
navigation-animation/src/androidTest/java/com/google/accompanist/navigation/animation/NavHostControllerTest.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavHostController.kt

Making sure the `rememberAnimatedNavController` API only changes the `AnimatedComposeNavigator` if the underlying navController changes. 
Also switched to using the `rememberAnimatedNavController` function in our tests.
Fixes #610

Fix rememberAnimatedNavController API

---

navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

Fixes #611
In some cases, the `sheetContent` composable from BottomSheetNavigator.kt might be composed before the NavHost has been composed, and thus the navigator is not attached yet. Added a flag for this.
Test: BottomSheetNavigatorTest#testComposeSheetContentBeforeNavigatorAttached

[Nav Material] Return empty back stack if navigator is not attached yet

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt

#623 
Calculating indicatorWidth, indicatorHeight and spacing with LocalDensity seems to solve this issue.
VerticalPagerIndicator  | HorizontalPagerIndicator
------------- | -------------

Fix active bullet offset

---

pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

Selected is designed to be used by controls such as radio buttons, which doesn't match our use case. Remove this for now to allow developers to set their own semantic meaning.
Fixes #599

[Pager] Don't set selected semantic property

---

checksum.sh

Finishes a comment in `checksum.sh` describing why the file hashes are sorted.

Finish checksum.sh sentence

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt
pager/api/current.api
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

- Make it non-null. If an animation isn't in progress we now return the current page.
- We now also return the current page if the offset is currently 0f.
Fixes #652
Fixes #654

[Pager] Tweaks to PagerState.targetPage

---

gradle/libs.versions.toml

Depend on [Navigation `2.4.0-alpha07`](https://developer.android.com/jetpack/androidx/releases/navigation#2.4.0-alpha07) to pull in the fixes from that release.

Update to depend on Navigation 2.4.0-alpha07

---

docs/insets.md

What's `ScrollableColumn`? Never heard of it. There's no such thing as pre-1.0 Compose, and the API was perfect from the very first alpha.

Remove reference to ScrollableColumn in doc

---

navigation-animation/README.md
navigation-material/README.md
permissions/README.md
placeholder-material/README.md
placeholder/README.md

Some modules were lacking the easy to find link inside their README files to the appropriate documentation that I found very neat in other modules. This commit adds the links in those modules too.

Add links to documentation on modules where it was missing

---

swiperefresh/build.gradle

As it is not used and will pull in unnecessary dependencies for consumers.

Remove swiperefresh's dependency on ui-tooling

---

navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/SheetContentHostTest.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/SheetContentHost.kt

Kinda similar to #741 - we were calling `show` too early. That meant that the `SwipeableState`/`ModalBottomSheetState`'s `anchors` wouldn't have been calculated properly yet. By default, a sheet will have two anchors: `Hidden` and `Expanded`. If `sheetHeight > containerHeight / 2`, the sheet should have a `HalfExpanded` state. For that, `ModalBottomSheetLayout` needs to know the sheet's height, making it two-pass. The effect we use to `show` the sheet got called on the first pass though, when the sheet content is composed to measure it, but the anchors didn't have the correct sheet height yet, causing the sheet to fully expand despite it being tall enough to have a `HalfExpanded` state.
This isn't a nice solution but in agreement with Matvei, it seems to be the most reasonable fix for the …

[Navigation Material] Fix Bottom Sheet Fully Expanding

---

navigation-material/api/current.api
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

Expose all public ModalBottomSheetState and SwipeProgress properties in BottomSheetNavigatorState

---

docs/navigation-animation.md

The `initial` and `target` parameters to each transition lambda have been replaced with the use of `AnimatedContentScope<NavBackStackEntry>` receiver scope, which provides the `initialState` and `targetState` properties.
As these aren't entirely obvious when looking at a code snippet, added some additional docs that talk about how this lambda is built and what it provides.

Update Navigation guide to match new API

---

systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt

This fixes #881 
The issue occurs with the `Activity`'s theme contains `android:windowLightStatusBars="true"`. In other words, the status bars icons are dark by default.
There was a bug in `androidx.core` in this case that prevented showing the light icons on API 30: https://issuetracker.google.com/issues/180881870.
This was marked as fixed, and released with `1.7.0` (which `accompanist` is using), but there is a follow-up issue: Depending on how the `WindowInsetsControllerCompat` is acquired, the workaround fixing the issue on API 30 may or may not be used: https://issuetracker.google.com/issues/207401542
In our case, we were using a codepath that doesn't have the workaround, meaning that we are still encountering the "fixed" issue (#881). By switching from `ViewCompat. …

Fix set status bar icons on API 30

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt

Fix the PagerState.targetPage when the currentPageOffset between -0.5f and 0f, the targetPage is currentPage + 1 which is wrong, it should be currentPage - 1.

PageState.targetPage didn't perform as we expected  when page offset between -0.5f and 0f.

---

navigation-animation/api/current.api
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedComposeNavigator.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavGraphBuilder.kt

Adding destination custom animations to the animation maps to ensure
they are considered when selecting the final animation.
Fixes #882

Fix destination animations being ignored

---

pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseHorizontalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseVerticalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

It could happen for example if the items were reordered.
Fixes #808

Update PagerState.currentPage when it is changed in LazyListState

---

gradle.properties
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt

We should only allow a single instance of an entry in either of the
visible entry lists.
#872

[Compose 1.0] Make visible entries a Set

---

docs/pager.md

As I was reading the pager documentation I noticed a very minor spelling mistake and a couple of missing words. This PR corrects both.

Spelling and grammar tweak for pager docs

---

docs/navigation-material.md
navigation-material/api/current.api
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/HalfExpandedTests.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

This adds a skip half expanded flag to the rememberBottomSheetNavigator() function thereby fixing #657 for the navigator only.
Discussion on this PR before rebase: https://github.com/google/accompanist/pull/957

[Material-Navigation] Add navigator-level skip half expanded flag for BottomSheetNavigator.kt

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseHorizontalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseVerticalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

Ported the behavior from ViewPager2
Fixes https://github.com/google/accompanist/issues/876

[Pager] Do not scroll more than 3 items as an optimization

---

docs/swiperefresh.md

Currently documentation only states that container needs to be scrollable. However, it needs to be **vertically** scrollable, which means that LazyRow does not count.
This update hopes to clarify that.
This fixes #823

[SwipeRefresh] Clarify that SwipeRefresh child needs to be vertically scrollable

---

insets-ui/src/main/java/com/google/accompanist/insets/ui/BottomNavigation.kt

Let Ripple pass through the navigation bar in `Navigation Gestures (left and right)` mode.
This will be consistent with the effect of the status bar.

Fix the edge of Ripple in BottomNavigation

---

gradle/libs.versions.toml
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/systemuicontroller/SystemBarsColorSample.kt
sample/src/main/res/values/themes.xml
systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt

This PR fixes #918 , where `@Preview` wasn't working with the `SystemUiController`.
The issues in this area (#881, #949) are fixed upstream in `androidx.core`, and should be available in the next release (and are available immediately in snapshot `8139767` and beyond). Those issues aren't directly fixed with this PR, so the `BEFORE` state will currently reproduce on API 30.
This PR just prepares for that update, where `ViewCompat.getWindowInsetsController` is the singular entry for `WindowInsetsControllerCompat` that will contain the workarounds.
BEFORE:
https://user-images.githubusercontent.com/4217560/151279075-a90b5dc7-0d8d-44fc-ab5a-47401fca5756.mp4
AFTER (with snapshot):
https://user-images.githubusercontent.com/4217560/151279079-54da2140-643a-45ba-a311-736d44a1a777.mp4

[SystemUiController] Add API 30 workaround for system bar appearance

---

gradle/libs.versions.toml

This is a followup to #986, bumping the version of `androidx.core` to the version that contains the upstream fix for #881 and #949.

Update androidx.core to 1.8.0-alpha04

---

web/src/main/java/com/google/accompanist/web/WebView.kt

I noticed that my web content does not fill the `WebView` composable completely. Instead, it wraps the content size. In my opinion the native webview should fill out the composable. So I simply added the `layoutParams`. What do you think?

[Webview] Make native webview fill parent WebView composable

---

swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefreshIndicator.kt

Fix the bug that the indicator's elevation is set to 0 when bouncing back after swipe or refresh.
Also slightly simplify the logic in `SwipeRefreshIndicator`.

[SwipeRefresh] Fix zero elevation when the indicator is bouncing back

---

docs/permissions.md

The `state` variable does not exist and might be confusing for the newcomers, thus it might be better to use `cameraPermissionState` in `when` statement.

[Permissions] Fix typo

---

gradle/libs.versions.toml
pager/api/current.api
pager/src/main/java/com/google/accompanist/pager/Pager.kt

Required deprecating one of the `flingBehavior` functions which use the deprecated `maximumFlingDistance` param.

[Pager] Upgrade to Snapper 0.2.0

---

web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Fixes #1037 
When providing a baseUrl to load html content relative to, it was being overriden during the update history call. This was due to the check assuming html data didn't have a URL when in fact it should be checking the baseUrl.
Added a test for this case
This brought up the edge case of navigating from html content with a baseurl to some other content, added a test to make sure that still works.

[Web] Fix baseUrl causing HTML data not to load

---

pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt

We will now update it once we scrolled more than a half of the next page without waiting for the scrolling to fully settle
Fixes https://github.com/google/accompanist/issues/1008

[Pager] Refactor how we update the current page

---

web/api/current.api
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Add properties to the WebViewState class to supply any received title and favicon from the loaded page to the caller.

[Web] Add properties for page title and icon to WebViewState

---

gradle/libs.versions.toml
sample/src/main/java/com/google/accompanist/sample/webview/BasicWebViewSample.kt
web/api/current.api
web/build.gradle
web/src/androidTest/AndroidManifest.xml
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

- Swap out the boolean for a `LoadingState` sealed class with a progress value
- Add test for loading state
MockWebServer was used to ensure an adequate turnaround time for the loading state to actually pass through the `Started` state. By using the same technique as other tests it never left `Finished`. I tried using HTML with meta tags to turn off any sort of caching but never saw the expected `Finished -> Started (*n) -> Finished` sequence.
Will likely conflict with https://github.com/google/accompanist/pull/1029 so I'll deal with that once things one or the other is merged.

[Web] Expose progress as part of the loading state

---

sample/src/main/java/com/google/accompanist/sample/webview/BasicWebViewSample.kt
web/api/current.api
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Currently this is just an early proof of concept, implementing the ability to control web view navigation from outside the composable (e.g. for wiring up a `TopAppBar` "up" button to the WebView's `goBack()` method).
I figured it would be good to get some general feedback on this implementation in an early stage before going ahead with docs, tests, etc.
I figured that this stuff made more sense as its own class outside of `WebViewState` as it's a case that not everyone will have to override, and because it's more "action" oriented than "state" oriented. This implementation also seems a bit more along the lines of similar constructs elsewhere in Compose like `InteractionSource`

[Web] Navigation Controls

---

web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

#1067 had a lint error in it that was only picked up after the merge as the lint version in main was ahead of this branch.

[Web] Fix new lint error in web

---

gradle/libs.versions.toml
systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt
systemuicontroller/src/sharedTest/kotlin/com/google/accompanist/systemuicontroller/SystemUiControllerTest.kt

Small version bump to `androidx.core`, which undeprecated the `WindowCompat.getInsetsController` method (which was previously deprecated).
This is a minor change on our side to use the non-deprecated version (and this won't break preview either!)
Upstream, the approach that promised to allow `ViewCompat.getWindowInsetsController` everywhere didn't work, as for some API versions direct access to the `Window` was required.
Therefore, `ViewCompat.getWindowInsetsController` was reverted to its original behavior but deprecated, since it would find the `Activity`'s `Window`. This wouldn't work when used from a `Dialog`, so `WindowCompat.getInsetsController` is the undeprecated version that requires explicitly passing the correct `Window`.
A related issue here is that `SystemUiController` …

[SystemUiController] Update androidx-core to 1.8.0-alpha06

---

sample/src/main/java/com/google/accompanist/sample/webview/BasicWebViewSample.kt
web/api/current.api
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Fixes #1095 
Fixes #1071 
Currently Accompanist Web sets it's own clients and doesn't provide a way to customise them. This limits the functionality and has created some obvious missing features. This is an attempt to expose the clients whilst maintaining the existing functionality. I did this via subclassing as I couldn't think of another way to do it, the clients themselves are classes not interfaces which limited the possibilities.
Open to other suggestions.
The other thing is I removed the `onError` callback as it was now duplicating functionality. I decided not to mark it as deprecated because this library was never released in a non-alpha version but I can create a deprecated version of it if needed.

[Web] Add a method to expose WebViewClient and WebChromeClient

---

web/api/current.api
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

I have a use case where I need to pass additional HTTP headers to `WebView.loadUrl()`.
While extending `WebContent.Url` I noticed that `state.content` is reassigned in several callback methods of `WebViewClient`, for example in `shouldOverrideUrlLoading()`. While `additionalHttpHeaders` are used for the initial `loadUrl()` call, this means that the state property `additionalHttpHeaders` is lost on reassignment. I'm not sure if this poses an issue and if so how to handle this situation.

[WebView] Add additionalHttpHeaders to WebContent.Url

---

web/api/current.api
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

[Web] Add an initializing state to WebView

---

.github/workflows/device-tests.yml

In the forked repository, it will still periodically execute the test.
I think this test could maybe be done in the main repository or executed once when there is a new pull request, otherwise, the forked repositories all get an email with the test processing results.

Disable the "device-tests.yml" test in the forked repository

---

sample/src/main/java/com/google/accompanist/sample/webview/BasicWebViewSample.kt
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Fixes #1164
Ensure the clients always reference the correct state object. Added a comment about why we don't use the normal apply method in the remember helpers.
Also updated the sample to closer represent the use case from the issue, which should be pretty common.

[Web] Fix url in remember not causing recomposition

---

placeholder/src/main/java/com/google/accompanist/placeholder/Placeholder.kt

In the original implementation of the placeholder modifier a `lastOutline` ref was used to cache the `Outline` returned by the `drawPlaceholder` method. An update was made that removed the assignment of the outline to the ref in this commit:
https://github.com/google/accompanist/commit/350f4b99fe9c04a074c9e39e25cf0eb7786ef2d7#r62458837
This change restores the ref assignment to make the outline cache function correctly.

[Placeholder] Fix outline cache in placeholder

---

appcompat-theme/build.gradle
drawablepainter/build.gradle
flowlayout/build.gradle
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
insets-ui/build.gradle
insets/build.gradle
internal-testutils/build.gradle
navigation-animation/build.gradle
navigation-material/build.gradle
navigation-material/src/main/java/com/google/accompanist/navigation/material/SheetContentHost.kt
pager-indicators/build.gradle
pager/build.gradle
permissions/build.gradle
placeholder-material/build.gradle
placeholder/build.gradle
sample/build.gradle
settings.gradle
swiperefresh/build.gradle
systemuicontroller/build.gradle
web/build.gradle

Fixed an issue in navigation material. It was setting hide called back to false too soon, removing the set fixes the issue. The flag is set back to false thanks to the remember being keyed with the backStackEntry

Compose 1.2.0-beta03

---

gradle/libs.versions.toml
sample/build.gradle
sample/src/main/java/com/google/accompanist/sample/webview/BasicWebViewSample.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Fixes #1177
AndroidViews just get rendered as grey placeholders in preview so just bail early.

[Web] Fix webview breaking preview

---

pager/api/current.api
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

targetPage is deprecated in favor of currentPage as currentPage property is now being updated right after we over scrolled the half of the previous current page. If you still think that you need targetPage, not currentPage please file a bug as we are planning to remove this property in future.

[Pager] Deprecate PagerState.targetPage

---

gradle/libs.versions.toml

Resolves #1118 .
Updates [snapper](https://github.com/chrisbanes/snapper) dependency to version `0.2.2`.
This version contains the fix for the above mentioned issue.
For further details, see: https://github.com/google/accompanist/issues/1118#issuecomment-1157410298

[Pager] Update snapper dependency to resolve target page skips on fling

---

docs/webview.md

In the documentation for the WebView wrapper, the name JavaScript appears to be written as “Javascript” in one place and “javascript” in another. This pull request corrects these two typos.

[WebView] Correct typos in documentation

---

navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/SheetContentHostTest.kt

result of `assertThat` is unused in `SheetContentHostTest`

[navigation material] use result of assertThat

---

sample/src/main/java/com/google/accompanist/sample/navigation/material/BottomSheetNavSample.kt

[Navigation] Fix overlapping elements in Sample Bottom Sheets layout

---

docs/navigation-material.md

In the documentation for Navigation Material, the following code sample is present:
```kotlin
@Composable
fun MyApp() {
val bottomSheetNavigator = rememberBottomSheetNavigator()
val navController = rememberNavController(bottomSheetNavigator)
ModalBottomSheetLayout(bottomSheetNavigator) {
NavHost(navController, Destinations.Home) {
composable(route = "home") {
...
}
bottomSheet(route = "sheet") {
Text("This is a cool bottom sheet!")
}
}
}
}
```
In the sixth line, `Destinations.Home` is used, but no such thing is defined anywhere in the documentation, making the code sample somewhat unclear. This pull request replaces `NavHost(navController, Destinations.Home)` with `NavHost(navController, "home")` to ensure that the code samples in the Navigation Material documentation donʼt include …

[Navigation Material] Remove usages of undefined `Destinations.Home` string from code samples in documentation

---

navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt

Since moving to using visibleEntries, if you change your start
destination dynamically, instead of dropping the graph and rebuilding,
the AnimatedNavHost crashes.
The reason for this crash is that setting the graph synchronously pops
the entire back stack, which clears all of the visibleEntries so there
is a frame in AnimatedNavHost where it fails to find any of the old
entries.
We should move setNavGraph over to using the popWithTransition function,
but there is pre-req works that needs to be done. So as a stop gap, we
will return null from visibleEntries and disable the animations on
AnimatedNavHost.
Fixes #1162

[Navigation Animation] Avoid crashing when the start destination changes

---

navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

We should be marking markTransitionComplete on the
transitionsInProgress, not the backStack.
Fixes #978

[Navigation Material] Mark transitionsInProgress complete in BottomSheetNavigator

---

sample/src/main/java/com/google/accompanist/sample/systemuicontroller/SystemBarsVisibilitySample.kt
systemuicontroller/api/current.api
systemuicontroller/src/main/java/com/google/accompanist/systemuicontroller/SystemUiController.kt
systemuicontroller/src/sharedTest/kotlin/com/google/accompanist/systemuicontroller/ActivityRememberSystemUiControllerTest.kt
systemuicontroller/src/sharedTest/kotlin/com/google/accompanist/systemuicontroller/ActivitySystemUiControllerTest.kt
systemuicontroller/src/sharedTest/kotlin/com/google/accompanist/systemuicontroller/DialogRememberSystemUiControllerTest.kt
systemuicontroller/src/sharedTest/kotlin/com/google/accompanist/systemuicontroller/DialogSystemUiControllerTest.kt

This PR exposes `SystemUiController.systemBarsBehavior`, which is just a small wrapper around `WindowInsetsControllerCompat.systemBarsBehavior`.
Since `SystemUiController` exposes `isSystemBarsVisible`, `isStatusBarVisible` and `isNavigationBarVisible`, it seems reasonable to also expose the behavior tweaking how those setters work.
This fixes #1205

[SystemUiController] Add support for systemBarsBehavior

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt

As reported in issue #1218, `pagerTabIndicatorOffset` doesnʼt work correctly in RTL layouts. This PR resolves the issue.
| Layout direction | Before | After |
| --- | --- | --- |
| LTR | https://user-images.githubusercontent.com/56888459/176960447-82ba04df-cbac-45d2-bc93-bcc630de5a91.mp4 | https://user-images.githubusercontent.com/56888459/176960778-53ef36b7-7ebc-45d5-99cf-95e37659a4df.mp4 |
| RTL | https://user-images.githubusercontent.com/56888459/176960636-359e9123-5382-40fb-81e2-971803eb3c04.mp4 | https://user-images.githubusercontent.com/56888459/176960896-8fa927c7-d56b-4d28-96dc-8ef25530c5ac.mp4 |

[Pager Indicators] Fix behavior of `pagerTabIndicatorOffset` in RTL layouts

---

pager/src/main/java/com/google/accompanist/pager/Pager.kt

Avoids recreating nested scroll connection in pager (and potentially recomposing it)

[Pager] Remember nested connection in Pager component

---

sample/src/main/java/com/google/accompanist/sample/systemuicontroller/DialogSystemBarsColorSample.kt

This PR just updates the dialog system ui controller sample to show off IME insets working (inside the fullscreen dialog)

[SystemUiController] Update SystemUiController samples

---

docs/systemuicontroller.md
sample/src/main/java/com/google/accompanist/sample/systemuicontroller/DocsSamples.kt

Reworks the primary docs entrance to the system ui controller module slightly.
First, it removes the reference to `MaterialTheme.colors.isLight`. This is M2 specific, and [doesn't exist](https://issuetracker.google.com/208860800) in M3 in favor of hoisting the decision directly.
Second, it replaces `SideEffect` with a `DisposableEffect` with keys. I could go either way here, but I'm less of a fan of the implicit nature in how `SideEffect` reruns. It's not super obvious that this wouldn't work when `useDarkIcons` changes:
```
val systemUiController = rememberSystemUiController()
var useDarkIcons by remember { mutableStateOf(false) }
SideEffect {
systemUiController.setSystemBarsColor(
color = Color.Transparent,
darkIcons = useDarkIcons
)
}
```

[SystemUiController] Update SystemUiController to hoist dark theme

---

.github/ISSUE_TEMPLATE/adapative-bug-report.md
adaptive/src/main/java/com/google/accompanist/adaptive/TwoPane.kt
docs/adaptive.md

Adds an new bug report type, and a `docs` entry with an overview of the new APIs. Also updated the public, built-in `*TwoPaneStrategy` creators to review mentioning of automatic fold handling since that is handled at the `TwoPane` level.

[Adaptive] Miscellaneous doc updates

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt

In the require() check, it checks the value is within [-1, 1], but the error message is different.
Correct the error message to fix.

[Pager] Correct the error message requireCurrentPageOffset

---

drawablepainter/build.gradle
drawablepainter/src/androidTest/kotlin/com/google/accompanist/drawablepainter/DrawablePainterTest.kt
drawablepainter/src/androidTest/kotlin/com/google/accompanist/drawablepainter/Drawables.kt
drawablepainter/src/main/java/com/google/accompanist/drawablepainter/DrawablePainter.kt

This PR fixes the bug when `DrawablePainter` overwrites bounds of the drawable instance when drawing it. It leads to incorrect behaviour of content scaling of `Image`.

[DrawablePainter] Fix overwriting bounds of drawable when drawing it via DrawablePainter

---

pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseHorizontalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseVerticalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

Previously we didn't add the itemSpacing to the size during the calculation which made the pageOffset to not be within [-0,5, 0.5] range.
Fixes https://github.com/google/accompanist/issues/1279

[Pager] Fix pageOffset calculation when itemSpacing is not 0

---

web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

[Web] Fix webview blocking js reload

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt

Fixes #1319
Before:
After:
Analogous change for vertical pager indicator.

[Pager indicators]Don't draw active dot indicators for empty pagers.

---

docs/permissions.md

Fix Permissions docs

---

.idea/codeStyles/Project.xml
.idea/kotlinc.xml
README.md
docs/swiperefresh.md
sample/src/main/java/com/google/accompanist/sample/placeholder/PlaceholderBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/placeholder/PlaceholderFadeSample.kt
sample/src/main/java/com/google/accompanist/sample/placeholder/PlaceholderShimmerSample.kt
sample/src/main/java/com/google/accompanist/sample/swiperefresh/DocsSamples.kt
sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshContentPaddingSample.kt
sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshCustomIndicatorSample.kt
sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshTweakedIndicatorSample.kt
sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshVerticalPagerSample.kt
swiperefresh/README.md
swiperefresh/api/current.api
swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt
swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefreshIndicator.kt
swiperefresh/src/sharedTest/kotlin/com/google/accompanist/swiperefresh/SwipeRefreshTest.kt

Deprecates `SwipeRefresh` in Accompanist.
Write documentation for migration to Compose Material PullRefresh.

[SwipeRefresh] Deprecate SwipeRefresh

---

navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt
sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt

NavHost should respect the z-order established by visibleEntries. This ensures that incoming Composables will be on top of exiting ones, except in the case of a pop it is expected that it is reversed.
Fixes: #1160

Base z-order on visibleEntries

---

sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/webview/WrappedContentWebViewSample.kt
sample/src/main/res/values/strings.xml
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Fixes #1297
WebView changes its layout engine based on its layoutParams. This PR converts from a Compose modifier into view layoutParams in order to support this. I thought this was a better integration than simply exposing the layoutParams parameter.

[Web] Fix WebView always filling max available space

---

pager/src/sharedTest/kotlin/com/google/accompanist/pager/HorizontalPagerScrollingContentTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/VerticalPagerScrollingContentTest.kt

When nested scrolling in a pager, if we don't scroll over half a pager before letting the fling start, we'll snap back after the fling finishes scrolling the inner list. In this PR I'm making the scrolling list to scroll over half a pager so when the fling finishes we can continue the scrolling towards the next page.

[Pager] Nested Scrolling list offset issue

---

README.md

Proposal to update the emoji for the testharness library to :clamp, to represent holding a composable in place to test it.

[Test Harness] Update test harness icon to 🗜

---

docs/testharness.md
sample/src/main/java/com/google/accompanist/sample/testharness/TestHarnessSample.kt
testharness/src/main/java/com/google/accompanist/testharness/ContextThemeWrapper.java
testharness/src/main/java/com/google/accompanist/testharness/TestHarness.kt

Adds a custom `ContextThemeWrapper` to work around the issue that currently causes `TestHarness` to fail in previews.
The cause of the crash is that `Context.createConfigurationContext` returns `null` for `BridgeContext` in layoutlib: https://cs.android.com/android/platform/superproject/+/master:frameworks/layoutlib/bridge/src/com/android/layoutlib/bridge/android/BridgeContext.java;l=1380;drc=58bd418e161b5d4fdde39b46523d3e49269117e3
`ContextThemeWrapper` uses this `Context.createConfigurationContext` internally and assumes it is not null, which causes the crash.
The `androidx.appcompat.view.ContextThemeWrapper` has a fallback mechanism for older API versions using a deprecated `Resources` constructor, so this PR adds a custom `ContextThemeWrapper` based on the appcompat one that uses that …

[Test Harness] Add custom ContextThemeWrapper to improve test harness behavior in previews

---

adaptive/src/sharedTest/kotlin/com/google/accompanist/adaptive/WearTest.kt
testharness/api/current.api
testharness/src/main/java/com/google/accompanist/testharness/TestHarness.kt

Add support for Wear to test harness.  
To replace existing test libraries like https://github.com/google/horologist/blob/1ab282cf951b0386650acfff3ee8ed8acaf2ea2d/compose-tools/src/main/java/com/google/android/horologist/compose/tools/RoundPreview.kt

[testharness] Add support for Wear to test harness

---

appcompat-theme/src/androidTest/AndroidManifest.xml
appcompat-theme/src/main/AndroidManifest.xml
drawablepainter/src/main/AndroidManifest.xml
flowlayout/src/main/AndroidManifest.xml
insets-ui/src/androidTest/AndroidManifest.xml
insets-ui/src/main/AndroidManifest.xml
insets/src/main/AndroidManifest.xml
navigation-animation/src/main/AndroidManifest.xml
navigation-material/src/main/AndroidManifest.xml
pager-indicators/src/main/AndroidManifest.xml
pager/src/main/AndroidManifest.xml
permissions/src/main/AndroidManifest.xml
placeholder-material/src/main/AndroidManifest.xml
placeholder/src/main/AndroidManifest.xml
swiperefresh/src/main/AndroidManifest.xml
systemuicontroller/src/main/AndroidManifest.xml
testharness/src/main/AndroidManifest.xml
themeadapter-appcompat/src/main/AndroidManifest.xml
themeadapter-core/src/main/AndroidManifest.xml
themeadapter-material/src/main/AndroidManifest.xml
themeadapter-material3/src/main/AndroidManifest.xml
web/src/main/AndroidManifest.xml

This makes it easier to import Accompanist into non-gradle build environments

Add minSdk info to AndroidManifest

---

settings.gradle

Currently, I'm still waiting for https://github.com/google/accompanist/pull/1437 to be merged. I was letting the accompanist as a composite build replace the original version. 
But this introduces a warning:
`Project accessors enabled, but root project name not explicitly set for 'accompanist'. Checking out the project in different folders will impact the generated code and implicitly the buildscript classpath, breaking caching.`
I believe the composite build will become more and more commonly used by the developer, which is why I am creating this simple PR.

[Gradle] Add root project name

---

navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt
sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt

The zIndex is currently based on the index of the entry from the list of visible entries available in the navigator. The visible entries get recreated each time the back stack changes and this means the index of the entries changes as well. When doing a pop, the zIndex of the ContentTransform is 0, when there is an additional pop, the zIndex of the new ContentTransform is also 0. Since both of them have the same value, the new ContentTransform is on top and that causes the pop enter transition to be on top.
If we provide the value of the back stack as the zIndex instead, each ContentTransform will increase in value as the stack gets larger, and when popping, the zIndex of outgoing entries will never be the same as the zIndex of incoming entries.
Fixes #1411

[Navigation Animation] Change zIndex to match navigator back stack

---

navigation-material/api/current.api
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/NavGraphBuilderTest.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/SheetContentHostTest.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/SheetContentHost.kt

This PR refactors our Navigation Material code after upstream updates to ModalBottomSheetLayout that address one-frame consistency and anchor update + reconciliation logic.
We now retain the back stack entry until all animations are completed.
|API|Status|
|---|---|
|public ctor BottomSheetNavigatorSheetState|internal ctor|
|BottomSheetNavigatorSheetState#offset|Deprecated|
|BottomSheetNavigatorSheetState#direction|Deprecated|
|BottomSheetNavigatorSheetState#progress|Deprecated|
- BottomSheetNavigator now uses moveable content under the hood
- The strategy for retaining bottom sheet back stack entries has changed to only dispose of them after the sheet has been hidden
Fixes: #772, #813, #910, #937, #1031, #1147, #1356

[Navigation Material] Update Navigation Material after ModalBottomSheetLayout bug fixes

---

gradle/libs.versions.toml

Updating the navigation library version to 2.5.3.
Release notes: https://developer.android.com/jetpack/androidx/releases/navigation#2.5.3

[Navigation] Bump Navigation version to 2.5.3

---

gradle/libs.versions.toml
sample/build.gradle
sample/src/main/java/com/google/accompanist/sample/webview/BasicWebViewSample.kt
web/api/current.api
web/src/androidTest/assets/test_link.html
web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Refactors WebView to not have to use `overrideUrlLoading`. This was leading to a lot of navigation edge cases that weren't properly handled. The new wrapping method should provide a more stable foundation to build upon.
| Deprecated | Replacement |
|---|---|
| **state.content.getCurrentUrl()** - **state.content** will also no longer track what url the webview is showing | **state.lastLoadedUrl** - Compose state object for the last url loaded by the WebView |
Fixes not following all redirects correctly
Fixes #1433
Fixes #1476

Refactor webview to not need to override url loading

---

web/src/main/java/com/google/accompanist/web/WebView.kt

Fixes https://issuetracker.google.com/243567497

[Web] Wrap webview in a viewgroup to workaround rare crash

---

web/src/main/java/com/google/accompanist/web/WebView.kt

Since you added a frame layout around the webview some websites have started get weird sizing problems.
The problem is visible on websites that isn't that tall and doesn't need scrolling. This PR fixes that issue.
I can also add that I think this can be simplified by setting match parent on the WebView and only use the height and width variables for the frame layout but don't know if the WebView would react differently then but I think that should work.

[WebView] Fixed sizing bug when showing a website that isn't covering all screen

---

drawablepainter/src/main/java/com/google/accompanist/drawablepainter/DrawablePainter.kt

This PR removes special case handling for BitmapDrawable. The previous handling was problematic in several ways:
1. bitmap in BitmapDrawable can be null. This was not handled.
2. BitmapDrawable handles density scaling internally. The density information was dropped in previous code, and the returned BitmapPainter would have wrong intrinsic size if specified density for drawable resource was different from device density, which is a common case in resource density fallback.
3. Mutation of BitmapDrawable after creating the Painter is ignored. But mutation of drawables with non-BitmapDrawable types are reflected in the returned DrawablePainter. This behavior difference seems not appropriate to me.
The ColorDrawable special case suffers from 3rd point but not 1st or 2nd point. If removal for …

[DrawablePainter] Fix rememberDrawablePainter for BitmapDrawable

---

navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

When our `sheetState.hide()` call got cancelled (e.g. when the activity/ModalBottomSheetLayout size changed, like when showing IME and adding ime padding), so would the whole produceState block. We now catch (and ignore) exceptions from `hide()` as there is no actionable resolution for us.
Test: Manual test, instrumented test blocked by b/269613287
Fixes: #1503, #1499

[Navigation Material] Catch exceptions when hiding sheet

---

gradle/libs.versions.toml
themeadapter-material3/src/main/java/com/google/accompanist/themeadapter/material3/Mdc3Theme.kt
themeadapter-material3/src/main/res/values/theme_attrs.xml

- Upgrade to MDC `1.8.0` which has been available since 24 Jan 2023.
- `1.8.0` includes outline variant so we should map it https://github.com/material-components/material-components-android/commit/ac6f13c0bec818568bf413883a24358bfa33dd3a
Fixes #1526

[Mdc3Theme] Upgrade MDC to 1.8 and map outline variant

---

adaptive/src/main/java/com/google/accompanist/adaptive/DisplayFeatures.kt

The previously incorrect usage of `produceState` would capture the very first instance of `windowLayoutInfo`, and not cancel collecting and switch to a new one if it changed.
This probably couldn't ever actually happen in practice since it would require the `Activity` to change (and somehow not tear down the entire UI?) but for reference it would be good to do this correctly.

[Adaptive] Fix technically incorrect usage of produceState

---

docs/pager.md

Removes a space which caused the markdown to render incorrectly.

[Pager] Fix typo in pager.md

---

docs/pager.md

**What's this?**
A minor edit to the pager migration table after learning from [Issue-1559](https://github.com/google/accompanist/issues/1559).
**What changed?**
Added clarification that `pageCount` parameter is needed to resolve the overloaded method supporting Compose `PagerState`.

[Pager Indicators] Documentation

---

.github/workflows/build.yml
gradle/libs.versions.toml
navigation-animation/src/androidTest/java/com/google/accompanist/navigation/animation/AnimatedNavHostTest.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt

Rollback navigation upgrade to latest stable

---

adaptive/build.gradle
adaptive/build.gradle.kts
gradle/libs.versions.toml

This is the first PR in a series to migrate the gradle files to use Kotlin DSL instead of Groovy.  Since having Kotlin DSL and Groovy in the same project works fine, I thought migrating module by module was okay.
The related issue is #1578.
I have split up the PR into two commits. The first one prepares the file to be migrated by using steps described in [these docs](https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html#prepare_your_groovy_scripts).  The second one is where I actually convert the file to `.kts` file and updates the rest of the file to be compatible with Kotlin DSL.
I have added a line to suppress unstable API usage, since a lot of the APIs here are marked incubating. What do you guys think about that?

[Adaptive] Migrate gradle module til Kotlin DSL

---

gradle/libs.versions.toml

After bumping to AGP 8.0 I think the publish task was broken.  Sorry about that. I could reproduce it locally with `gradle publishToMavenLocal`. Bumping this version fixed the issue locally. Would be nice to test this thoroughly before merging since it minor version bump. Is there a better way to test this than running `gradle publishToMavenLocal`?

[All] Bump vanniktechPublish plugin version

---

.github/workflows/publish-docs.yml
build.gradle
gradle/libs.versions.toml
mkdocs.yml

This fixes the NoSuchMethodError exception when running the `dokkaHtmlMultiModule` task that appeared after upgrading Gradle to 8.1 (https://github.com/Kotlin/dokka/issues/2796). 
This also brings a new UI for the API documentation pages.
Turned on alternate style on the Tabbed extension of the `mkdocs-material` to fix search on internal doc pages (fixes #1533). 
Also locked the major version of the `mkdocs-material` to prevent uncontrolled updates in the future and added the `gradle/gradle-build-action@v2` action to the publishing documentation workflow as in other workflows

[Documentation] Update Dokka to 1.8.10, Fix search

---

docs/permissions.md

Probably the word "the" was duplicated

[Permissions] Fixes typo

---

insets-ui/build.gradle
insets-ui/build.gradle.kts

Migrating the `:insets-ui` module to Kotlin DSL.
The testing I have done for this is to check that it syncs and builds the sample application. Let me know if there is any other test than what the CI runs that you want me to run as well.

[Insets-ui] Migrate build gradle file to Kotlin DSL

---

appcompat-theme/build.gradle
appcompat-theme/build.gradle.kts

Following up #1578 and relating to #1579 
Migrating the `:appcompat-theme` module to Kotlin DSL.

[AppCompatTheme] Migrate AppCompat-Theme gradle file to Kotlin DSL

---

drawablepainter/build.gradle
drawablepainter/build.gradle.kts

Migrating the `drawablepainter` module to Kotlin DSL.
I'm a bit unsure about the lint lambda textOutout. Maybe that should be in the build file or test result folder or something. I will update it to what we decide in https://github.com/google/accompanist/pull/1579#discussion_r1167980394.

[DrawablePainter] Migrate drawablepainter module gradle file to Kotlin DSL

---

flowlayout/build.gradle
flowlayout/build.gradle.kts

Migrating the ` :flowlayout` module to Kotlin DSL.

[FlowLayout] Migrate gradle module to Kotlin DSL

---

insets/build.gradle
insets/build.gradle.kts

Migrating the `:insets` module to Kotlin DSL.

[Insets] Migrate gradle file to Kotlin DSL

---

internal-testutils/build.gradle
internal-testutils/build.gradle.kts

Migrating the `:internal-testutils` module to Kotlin DSL.
The testing I have done for this is to check that it syncs and builds the sample application. Let me know if there is any other test than what the CI runs that you want me to run as well.

[Internal-testutils] Migrate gradle files to Kotlin DSL

---

navigation-animation/build.gradle
navigation-animation/build.gradle.kts

Migrating the `:navigation-animation` module to Kotlin DSL.
Testing

[Navigation-animation] Migrate gradle file to Kotlin DSL

---

pager/build.gradle
pager/build.gradle.kts

Migrating the `:pager` module to Kotlin DSL.
Testing

[Pager] Migrate build gradle file to Kotlin DSL

---

navigation-material/build.gradle
navigation-material/build.gradle.kts

Migrating the `:navigation-material` module to Kotlin DSL.
Testing

[Navigation-Material] Migrate build gradle file to Kotlin DSL

---

pager-indicators/build.gradle
pager-indicators/build.gradle.kts

Migrating the ` :pager-indicator` module to Kotlin DSL.

[Pager-Indicator] Migrate build gradle to Kotlin DSL

---

placeholder-material/build.gradle
placeholder-material/build.gradle.kts

Migrating the `:placeholder-material` module to Kotlin DSL.

[Placeholder-Material] Migrate cradle file to Kotlin DSL

---

placeholder-material3/build.gradle
placeholder-material3/build.gradle.kts

Migrating the `:placeholder-material3` module to Kotlin DSL.

[Placeholder-Material3] Migrate build gradle file to Kotlin DSL

---

placeholder/build.gradle
placeholder/build.gradle.kts

Migrating the `:placeholder` module to Kotlin DSL.

[Placeholder] Migrate gradle file to Kotlin DSL

---

gradle/libs.versions.toml
sample/build.gradle
sample/build.gradle.kts

Migrating the `:sample`  module to Kotlin DSL.

[Sample] Migrate gradle file to Kotlin DSL

---

gradle/libs.versions.toml

Update to Navigation 2.6.0-rc02 to automatically make all fixes since alpha08 available to Accompanist users.
Also update
- Activity Compose to 1.7.2
- Lifecycle Common Java8 to 2.6.1
Since those are also transitive dependencies of Navigation 2.6.0-rc02.
Fixes #1635 
Fixes #1638

[Navigation Animation] Update to Navigation 2.6.0-rc02

---

settings.gradle
settings.gradle.kts

Migrating the `settings.gradle` file  to Kotlin DSL.
Used this (https://docs.gradle.com/enterprise/gradle-plugin/) to check the gradle enterprise configuration was correct

[Settings gradle] Migrate settings.gradle to Kotlin DSL

---

web/build.gradle
web/build.gradle.kts
web/proguard-rules.pro

Migrating the `:web` module to Kotlin DSL.

[Web] Migrate gradle module to Kotlin DSL

---

themeadapter-material3/build.gradle
themeadapter-material3/build.gradle.kts

Migrating the `:themeadapter-material3` module to Kotlin DSL.

[ThemeAdapter-Material3] Migrate gradle module to Kotlin DSL

---

themeadapter-material/build.gradle
themeadapter-material/build.gradle.kts

Migrating the `:themeadapter-material` module to Kotlin DSL.

[ThemeAdapter-Material] Migrate gradle module to Kotlin DSL

---

themeadapter-appcompat/build.gradle
themeadapter-appcompat/build.gradle.kts

Migrating the `:themeadapter-appcompat` module to Kotlin DSL.

[ThemeAdapter-AppCompat] Migrate gradle module to Kotlin DSL

---

permissions/build.gradle
permissions/build.gradle.kts

Migrating the `:permissions` module to Kotlin DSL.

[Permissions] Migrate build gradle to Kotlin DSL

---

swiperefresh/build.gradle
swiperefresh/build.gradle.kts

Migrating the `:swiperefresh` module to Kotlin DSL.

[Swiperefresh] Migrate gradle module to Kotlin DSL

---

gradle/libs.versions.toml
navigation-animation/src/androidTest/java/com/google/accompanist/navigation/animation/NavHostControllerTest.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavGraphBuilder.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavHostController.kt

With navigation-animation migrated back to androidx navigation, we are deprecating accompanist navigation-animation with first step as delegating its implementation to androidx navigation.
Source breaking change -- navigation-animation migrated all internal usages of AnimatedComposeNavigator to ComposeNavigator. This means by default, animated NavHostController will only contain `ComposeNavigator` and no longer contain any `AnimatedComposeNavigator`. Code references to `AnimatedComposeNavigators` such as its retrieval from navigatorProvider may be impacted if none were manually added.
Test: ./gradlew navigation-aninmation:cC
Issue: #1646

[Navigation-animation] Delegate navigation-animation impl to androidx navigation

---

README.md

Adjusts the main README links by moving `Flow Layouts` to the other deprecated libraries.

[Docs] Move flow layouts to deprecated section

---

themeadapter-core/build.gradle
themeadapter-core/build.gradle.kts

Migrating the `:themeadapter-core` module to Kotlin DSL.

[ThemeAdapter-Core] Migrate gradle module to Kotlin DSL

---

testharness/build.gradle
testharness/build.gradle.kts

Migrating the `:testharness` module to Kotlin DSL.

[Testharness] Migrate gradle module to Kotlin DSL

---

systemuicontroller/build.gradle
systemuicontroller/build.gradle.kts

Migrating the `:systemuicontroller` module to Kotlin DSL.

[SystemUIController] Migrate gradle module to Kotlin DSL

---

docs/flowlayout.md

The Horizontal and Vertical classes don't exist, they should just be Arrangement

[FlowLayout] Fix error in migration guide

---

sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/permissions/RequestMultiplePermissionsSample.kt

fixes #1679.
RequestMultiplePermissionsSample was using READ_EXTERNAL_STORAGE, but this permission was removed at API Level 33 for more detailed items. It leads to the state where rememberMultiplePermissionsState() never count it as approved whereas launchMultiplePermissionRequest() will never ask the user for it as a valid permission, and the entire sample never gets to the "both approved" state.
Use another permission entry which is still valid at any API level.

[Permissions] Alter use of READ_EXTERNAL_STORAGE permission from permissions samples.

---

web/src/main/java/com/google/accompanist/web/WebView.kt

In this [PR](https://github.com/google/accompanist/pull/1483), Ben wrapped the Webview with a Framelayout to workaround rare crash. However, this led to the problem that the nested scroll does not work now. Since the AndroidViewHolder use view?.isNestedScrollingEnabled to determine whether the child view support nested scroll. It works well before this change because Webview supports nested scroll but failed now since FrameLayout does not. I opened an [issue](https://github.com/google/accompanist/issues/1652) about this problem and Ben approved me to remove the Framelayout first to workaround this issue. Thus I finished it and submit this PR
Fixes #1652

[Web]Remove the wrapper of webview to solve nestedscroll issue

---

docs/insets.md
insets-ui/src/main/java/com/google/accompanist/insets/ui/BottomNavigation.kt
insets-ui/src/main/java/com/google/accompanist/insets/ui/Scaffold.kt
insets-ui/src/main/java/com/google/accompanist/insets/ui/TopAppBar.kt
insets-ui/src/sharedTest/kotlin/com/google/accompanist/insets/ScaffoldTest.kt

This functionality is available in Compose Material 1.5.0

[Insets-UI] Deprecate insets UI

---

web/src/androidTest/kotlin/com/google/accompanist/web/WebTest.kt
web/src/main/java/com/google/accompanist/web/WebView.kt

Adds the postUrl function to the WebView
Fixes #1612

[WebView] ✨ Expose the postUrl function via the WebView Composable

---

gradle.properties
gradle/libs.versions.toml
sample/src/main/java/com/google/accompanist/sample/adaptive/NavDrawerFoldAwareColumnSample.kt
sample/src/main/java/com/google/accompanist/sample/adaptive/NavRailFoldAwareColumnSample.kt

Upgrade Compose to 1.6.0-alpha06

---

gradle/libs.versions.toml
permissions-lint/build.gradle
permissions-lint/build.gradle.kts

Migrating the `:permissions-lint` module to Kotlin DSL.

[Permissions-Lint] Migrate gradle file to Kotlin DSL

---

docs/placeholder.md

Small formatting change so the warning message in the docs shows within the warning box rather than under it.
How it shows currently on https://google.github.io/accompanist/placeholder/
How I'd expect it to show (as seen on other pages)

[Placeholder documentation] Show deprecated message within the warning box

---

docs/systemuicontroller.md
docs/themeadapter-appcompat.md
docs/themeadapter-core.md
docs/themeadapter-material.md
docs/web.md

Some pages are currently incorrectly formatted so the warning boxes don't have text in them
This PR just changes the formatting so they show correctly.
The warning boxes (and caution boxes) should show with text inside it as you see on docs pages like [insets](https://google.github.io/accompanist/insets/)
I [previously made this fix](https://github.com/google/accompanist/pull/1724) for the placeholder page but didn't realise there is the same problem in other places. This PR address all the places I found

[Documentation] Fix warning box/text in docs

---

docs/flowlayout.md

Update the style of the deprecated message for FlowLayout so it shows nicely in the docs
I.e. with the warning box similar to insets and other pages
Also rearrange the content so it's easy to understand new vs old with the seperate "migration" and "original docs" sections like on other docs pages, e.g. [insets](https://google.github.io/accompanist/insets/)

[FlowLayout Documentation] Update flowlayout.md

---

navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

If there is a nested NavGraph under the current bottomSheet destination and you do a back press, instead of the bottomSheet which is the topmost destination being popped, the nested NavHost underneath will be popped instead. This is caused by bottomSheet not properly intercepting back presses.
This change added a BackHandler to ensure that bottomSheets correctly respect the system back hierarchy for back events.
Fixes: #1726

[Navigation Material] Ensure Navigation Material properly handles back for nested nav

---

docs/themeadapter-material3.md

The warning looks not how it supposed to be

[ThemeAdapter-Material3] Fix warning in docs

---

README.md
adaptive/build.gradle.kts
adaptive/src/sharedTest/kotlin/com/google/accompanist/adaptive/TwoPaneTest.kt
docs/testharness.md
gradle/libs.versions.toml
pager/build.gradle.kts
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseHorizontalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseVerticalPagerTest.kt
sample/src/main/java/com/google/accompanist/sample/testharness/TestHarnessSample.kt
testharness/api/current.api
testharness/build.gradle.kts
testharness/src/main/java/com/google/accompanist/testharness/TestHarness.kt
testharness/src/sharedTest/kotlin/com/google/accompanist/testharness/TestHarnessTest.kt
testharness/src/sharedTest/kotlin/com/google/accompanist/testharness/TestHarnessTestApi23.kt

Deprecates testharness with the replacement of `DeviceConfigurationOverride`.
This PR also replaces the internal usage in some other module's tests, and provides a migration guide to the new methods.

[TestHarness] Deprecate testharness

---

adaptive/src/sharedTest/kotlin/com/google/accompanist/adaptive/TwoPaneTest.kt
gradle/libs.versions.toml

Removes the TODOs in the `adaptive` tests, after the fix landed upstream.

Remove TODOs for DeviceConfigurationOverride

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt

Fixes #1744.
The deprecation was intended to apply only to the old overload above, but was presumably copy-pasted by accident.

[pager-indicators] Drop false-positive deprecation of pagerTabIndicatorOffset()

---

docs/navigation-material.md
navigation-material/api/current.api
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/NavGraphBuilderTest.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/SheetContentHostTest.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheet.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/NavGraphBuilder.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/SheetContentHost.kt
sample/src/main/java/com/google/accompanist/sample/navigation/material/BottomSheetNavSample.kt

Now that Compose Material 1.7.0-alpha04 is out it offers the same functionality as Accompanist Navigation Material.
This deprecates all of the classes and functions
Test: ./gradlew navigation-material:cc

[Navigation Material] Deprecate navigation-material APIs

---

README.md

Update README.md to deprecate navigation-material

---

.github/workflows/build.yml
.idea/deploymentTargetSelector.xml
flowlayout/src/sharedTest/kotlin/com/google/accompanist/flowlayout/LayoutTest.kt
gradle.properties
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/SheetContentHostTest.kt
permissions/src/androidTest/AndroidManifest.xml
permissions/src/androidTest/java/com/google/accompanist/permissions/MultipleAndSinglePermissionsTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/MultiplePermissionsStateTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/PermissionStateTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/RequestMultiplePermissionsTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/RequestPermissionTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/TestUtils.kt
permissions/src/main/java/com/google/accompanist/permissions/PermissionsUtil.kt
sample/src/main/java/com/google/accompanist/sample/adaptive/DraggableFoldAwareColumnSample.kt
sample/src/main/java/com/google/accompanist/sample/navigation/animation/AnimatedNavHostSample.kt
testharness/src/sharedTest/kotlin/com/google/accompanist/testharness/TestHarnessTest.kt

Fixes #1778 
I will roll this out as a release so have set the version number as well

Raise Compose version to 1.7.0-beta04

---

docs/insets.md

Fix insets-ui migration step

---

permissions/api/current.api
permissions/src/main/java/com/google/accompanist/permissions/MultiplePermissionsState.kt
permissions/src/main/java/com/google/accompanist/permissions/PermissionState.kt

Spinning this out while the fate of https://github.com/google/accompanist/pull/1793 hangs in the balance :sweat_smile:

[Permissions] Support calling rememberPermissionState in a Compose preview

---

build-logic/convention/build.gradle.kts
build-logic/convention/src/main/kotlin/com/google/accompanist/BundleInsideHelper.kt
gradle/libs.versions.toml
permissions-lint/build.gradle.kts
permissions-lint/src/main/java/com/google/accompanist/permissions/lint/util/ComposableUtils.kt
permissions-lint/src/main/java/com/google/accompanist/permissions/lint/util/KotlinMetadataUtils.kt
permissions-lint/src/main/java/com/google/accompanist/permissions/lint/util/Names.kt
permissions-lint/src/main/java/com/google/accompanist/permissions/lint/util/PsiUtils.kt

b/379173583
Updated lint set up to match AndroidX
Tested by unzipping `permissionsRelease.aar`, then unzipping the bundled lint.jar and manually verifying that `kotlin/metadata` has been moved to `androidx/lint/kotlin/metadata`

Fix issue bundling kotlin metadataJvm in permissions lint
