build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/build.gradle
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
mdc-theme/build.gradle

Also added some caching of `Paint` instances as they're expensive to create.

Update to Compose v0.1.0-dev11

---

coil/README.md

Clarify Coil's GIF support in README

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
gradle/wrapper/gradle-wrapper.properties
mdc-theme/src/androidTest/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeTest.kt
mdc-theme/src/main/java/dev/chrisbanes/accompanist/mdctheme/MaterialThemeFromMdcTheme.kt

Also updated to AGP 4.1.0-alpha10

Update to Compose + UI v0.1.0-dev12

---

.github/workflows/build.yml
.github/workflows/release-management.yml
README.md

Needed to fi refs in ci config and README

Update main branch refs

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
sample/build.gradle

- AGP 4.2.0-alpha05
- Update ktlint
- Remove kapt from sample

Misc improvements

---

.github/workflows/build.yml

JDK 11 seems to be flakey on the Mac runners

Go back to JDK 1.8 on Actions

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
gradle.properties

Update to Compose 1.0.0-alpha02

---

build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
deploy_docs.sh
docs/updating.md
docs/using-snapshot-version.md
gradle.properties
mkdocs.yml

- Automated the version prefix when Compose snapshot versions

Add doc to help maintainers update this library

---

build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/build.gradle
coil/src/main/java/dev/chrisbanes/accompanist/coil/Crossfade.kt
sample/build.gradle
sample/src/main/java/dev/chrisbanes/accompanist/sample/coil/CoilBasicSample.kt

Required manually applying the Compose Kotlin Compiler plugin.

Update to Compose SNAPSHOT 6854728

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt

Also AGP 4.2.0-alpha12 & ktlint 0.39.0.

Update to snapshot 6860046

---

README.md

I wasn't sure if you intentionally left this out or accidentally forgot. Here's a PR just in case. :)

Add glide to top-level readme

---

.github/ci-gradle.properties
.github/workflows/build.yml
gradle.properties

Not sure how, but parallel compilation, caching and configuration-on-demand were disabled.

Fix CI build speed

---

imageloading-core/src/main/java/dev/chrisbanes/accompanist/imageloading/ImageLoad.kt

This replaces some existing code which achieves the same pattern.

[Image Loading] Use rememberUpdatedState

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
imageloading-core/api/imageloading-core.api
insets/api/insets.api

Required update to Kotlin 1.4.20

Update to Compose SNAPSHOT 6989480

---

build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/build.gradle
generate_docs.sh
glide/build.gradle
imageloading-core/build.gradle
imageloading-testutils/build.gradle
insets/build.gradle
mkdocs.yml
picasso/build.gradle

Dokka's GFM renderer doesn't output what we expected, so we're moving to the HTML docs instead.

Migrate to Dokka MultiModule and HTML docs

---

coil/api/coil.api
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
glide/api/glide.api
glide/src/main/java/dev/chrisbanes/accompanist/glide/GlideImage.kt

To match the Compose library. See: https://issuetracker.google.com/159982740

Rename *Constants to *Defaults

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
insets/api/insets.api
insets/build.gradle
insets/src/main/java/dev/chrisbanes/accompanist/insets/ImeNestedScrollConnection.kt
insets/src/main/java/dev/chrisbanes/accompanist/insets/SimpleImeAnimationController.kt
sample/src/main/java/dev/chrisbanes/accompanist/sample/insets/ImeAnimationSample.kt

Support for controlling the device IME via nested scroll

---

buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
insets/build.gradle
insets/src/main/java/dev/chrisbanes/accompanist/insets/ImeNestedScrollConnection.kt
insets/src/main/java/dev/chrisbanes/accompanist/insets/Insets.kt

Doing so allows IME animations to work on devices before API 30. 🎉
_Video incoming_

[Insets] Use WindowInsetsAnimationCompat

---

appcompat-theme/build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/build.gradle
glide/build.gradle
gradle/wrapper/gradle-wrapper.properties
imageloading-core/build.gradle
imageloading-testutils/build.gradle
insets/build.gradle
picasso/build.gradle
sample/build.gradle

Upgraded AGP to 7.0.0-alpha05 to make it work with Android Studio Arctic Fox Canary 5

Bumped AGP to 7.0.0-alpha05

---

glide/src/androidTest/java/dev/chrisbanes/accompanist/glide/GlideTest.kt
glide/src/main/java/dev/chrisbanes/accompanist/glide/GlideImage.kt

Glide seems to perform all sorts of implicit and automatic behavior attached to the host lifecycle. To stop that, we now use the application context as the source for our default RequestManager.
Also updated our coroutine wrapper to swallow/no-op if Glide calls our listener/target a second time.
Fixes #196

Fix GlideImage crashing when resumed

---

coil/api/coil.api
coil/src/main/java/dev/chrisbanes/accompanist/coil/Coil.kt
glide/api/glide.api
glide/src/main/java/dev/chrisbanes/accompanist/glide/GlideImage.kt
insets/api/insets.api
insets/src/main/java/dev/chrisbanes/accompanist/insets/Insets.kt
picasso/api/picasso.api
picasso/src/main/java/dev/chrisbanes/accompanist/picasso/Picasso.kt

Remove in preparation for the next release

Remove all deprecated code

---

.idea/codeStyles/Project.xml
imageloading-core/src/main/java/dev/chrisbanes/accompanist/imageloading/MaterialLoadingImage.kt

- We now fade in each painter (if it changes)
- Updated to new transition best practices

Update image fade

---

appcompat-theme/build.gradle
buildSrc/src/main/java/dev/chrisbanes/accompanist/buildsrc/dependencies.kt
coil/build.gradle
glide/build.gradle
imageloading-core/build.gradle
imageloading-testutils/build.gradle
insets/build.gradle
picasso/build.gradle

Had to disable some Lint warnings, due to the mismatches with libraries

Update to AGP 7.0.0-alpha09

---

coil/src/main/java/com/google/accompanist/coil/Coil.kt

Fix crash when Coil is used with ConstraintLayout and dimensions are set independently

Fix crash when one constraint is set before the other

---

buildSrc/src/main/java/com/google/accompanist/buildsrc/dependencies.kt

Update AndroidX Core to 1.5.0-beta03

---

pager/src/main/java/com/google/accompanist/pager/PagerIndicator.kt
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/pager/DocsSamples.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerWithIndicatorSample.kt
sample/src/main/res/values/strings.xml

Adding a PagerIndicator Composable with flexible configuration.
I was not shure if the pager module itself is the right place or if it should be an individual module. 
Demo:
https://user-images.githubusercontent.com/878307/111903106-db7eea80-8a40-11eb-8216-759b482283d6.mp4

[Pager] Added a PagerIndicator composable

---

pager/api/pager.api
pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
sample/build.gradle
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerTransitionSample.kt
sample/src/main/res/values/strings.xml

Also added a sample which adds item transitions, such as a fade-in/out and light parallax effect.

[Pager] Add PagerState.calculateCurrentOffsetForPage() ext-fun 

---

pager/api/pager.api
pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/VerticalPagerTest.kt
pager/src/main/java/com/google/accompanist/pager/Pager.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/VerticalPagerBasicSample.kt

Allows apps to add spacing in between items.

[Pager] Add itemSpacing parameter

---

sample/src/main/java/com/google/accompanist/sample/pager/NestedPagersSample.kt

- Fixed `NestedPagersSample` title text.

[Sample]Fixed NestedPagersSample title

---

appcompat-theme/build.gradle
coil/build.gradle
flowlayout/build.gradle
glide/build.gradle
imageloading-core/build.gradle
imageloading-testutils/build.gradle
insets/build.gradle
pager-indicators/build.gradle
pager/build.gradle
systemuicontroller/build.gradle

Much speed. Such time back.
Before PR: tests on CI take 22-24 minutes.
With PR: _TODO_

[All] Disable window animations during tests

---

sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/swiperefresh/SwipeRefreshCustomSample.kt
sample/src/main/res/values/strings.xml

Adds a sample with an indicator that has custom color, shape, elevation, etc.
https://user-images.githubusercontent.com/12491712/114207242-75f58e00-995c-11eb-9867-0db1ddbf6c70.mp4

Add SwipeRefresh custom sample

---

sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerTransitionSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerWithIndicatorSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/NestedPagersSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/PagerSampleItem.kt
sample/src/main/java/com/google/accompanist/sample/pager/VerticalPagerBasicSample.kt
sample/src/main/java/com/google/accompanist/sample/pager/VerticalPagerWithIndicatorSample.kt

Starts re-using pager item implementations rather than having 4/5 copies.

Tidy up Pager samples

---

docs/insets.md

Interlinks between the insets and system ui controller docs.
Fixes #315

Add link to System UI Controller

---

coil/api/coil.api
coil/src/main/java/com/google/accompanist/coil/Coil.kt
glide/api/glide.api
glide/src/main/java/com/google/accompanist/glide/Glide.kt
imageloading-core/api/imageloading-core.api
imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt

Allows us to define a fixed type which is clearer.

Migrate ShouldRefetchOnSizeChange to fun interface

---

imageloading-core/src/main/java/com/google/accompanist/imageloading/DrawablePainter.kt
imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt

Allow nullable parameters to rememberDrawablePainter()

---

README.md

link  swipe-to-refresh library in README to be consistent with other libraries

Update README.md to include swipe-to-refresh link

---

docs/insets.md
sample/src/main/java/com/google/accompanist/sample/insets/DocsSamples.kt
sample/src/main/java/com/google/accompanist/sample/insets/EdgeToEdgeLazyColumn.kt
sample/src/main/java/com/google/accompanist/sample/insets/InsetAwareLayouts.kt

[Insets] Doc fixes

---

imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt

[ImageLoad] Use height when requesting size

---

pager/src/androidTest/java/com/google/accompanist/pager/HorizontalPagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/PagerTest.kt
pager/src/androidTest/java/com/google/accompanist/pager/VerticalPagerTest.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt

[Pager] Fix scrolling last item snapping back to previous item

---

docs/swiperefresh.md
swiperefresh/src/main/java/com/google/accompanist/swiperefresh/SwipeRefresh.kt

[SwipeRefresh] Make scrollable requirements clearer in docs

---

glide/src/main/java/com/google/accompanist/glide/Glide.kt

Glide is aggressive at recycling bitmaps when it doesn't really need to any more. Currently we seem to be drawing recycled bitmaps when clearing the request. For now we'll just not cancelled the request, which should have minimal effect anyway.
Fixes #419

[Glide] Stop clearing Glide requests

---

coil/src/main/java/com/google/accompanist/coil/Coil.kt
glide/src/main/java/com/google/accompanist/glide/Glide.kt
gradle/libs.versions.toml

Also upgraded to Kotlin 1.5.0 and Coroutines 1.5.0.

Update to Compose SNAPSHOT 7392605

---

build.gradle

See https://blog.jetbrains.com/kotlin/2020/07/kotlin-1-4-m3-generating-default-methods-in-interfaces/
This should bring down the AAR size down slightly.

Enable default methods in interfaces

---

imageloading-core/src/main/java/com/google/accompanist/imageloading/LoadPainter.kt

Currently we don't have a fallback, so the loaded image could be _huuuugeeee_.

[ImageLoad] Fallback to parent view size as default maximum request size

---

appcompat-theme/build.gradle
build.gradle
coil/build.gradle
glide/build.gradle
gradle/libs.versions.toml
imageloading-core/build.gradle
imageloading-testutils/build.gradle
insets-ui/build.gradle
insets/build.gradle
pager-indicators/build.gradle
pager/build.gradle
placeholder-material/build.gradle
placeholder/build.gradle
swiperefresh/build.gradle
systemuicontroller/build.gradle

Removed unnecessary/unused config.

[All] Tidy up Gradle configs

---

.github/workflows/build.yml
.github/workflows/device-tests.yml
permissions/src/androidTest/java/com/google/accompanist/permissions/MultipleAndSinglePermissionsTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/RequestPermissionTest.kt
scripts/run-device-tests.sh
systemuicontroller/src/androidTest/java/com/google/accompanist/systemuicontroller/SystemUiControllerTest.kt

Fixes tracked in #490 and #491

Mark CI flaky tests as flaky

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt

Hopefully fix scroll and flings causing NPEs
Fixes #485

[Pager] Coerce scroll/fling values into the correct range

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt

New implementation employs the actual floorMod algorithm from JDK 1.8 by using floorDiv. This implementation fixes Integer overflow possibility.

[Pager] Fix floorMod function in PagerState

---

permissions-lint/build.gradle
permissions/build.gradle

[Permissions] Lint Jar contains required dependencies

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/ZeroPageCountTest.kt

[Pager] Ensure that we don't create content when count=0

---

gradle/libs.versions.toml

Also updated Kotlin to 1.5.21 and Coroutines 1.5.1.

Update to Compose SNAPSHOT 7584688

---

permissions-lint/src/main/java/com/google/accompanist/permissions/lint/util/ComposableUtils.kt

Merges [this AOSP fix](https://android-review.googlesource.com/c/platform/frameworks/support/+/1773705) that solves the issue of some Lint checks not appearing in the IDE.

[Permissions lint] Merge aosp/1773705 changes

---

docs/navigation-animation.md
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavHostController.kt

Fixed the README docs to reflect the most recent changes to the library.
Added java docs to rememberAnimatedNavController API.

Correcting the docs for Navigation Animation

---

docs/navigation-animation.md
docs/navigation-material.md

Fix Navigation Sample Links

---

sample/src/main/AndroidManifest.xml
sample/src/main/res/values/strings.xml

Coil and Glide were removed from this project but six activities related to either of them are remaining in Manifest file. 
For example, clicking on "Coil: Lazy Grid" button in ListActivity causes crash and the log is as following: 
```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.google.accompanist.sample/com.google.accompanist.sample.coil.CoilLazyGridSample}: java.lang.ClassNotFoundException: Didn't find class "com.google.accompanist.sample.coil.CoilLazyGridSample"
```

Remove unresolved activities

---

drawablepainter/build.gradle

Update `drawablepainter` to depend on Compose UI

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

[Pager] Fix pageCount change not updating layout

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerIndicator.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt

#645
Replace not-null assertion operator with elvis operator and add coerceAtLeast(0) to avoid IllegalArgumentException caused by coerceIn

Fix NPE on pager indicator

---

navigation-material/api/current.api
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

Expose ModalBottomSheetState's offset from Navigator's state

---

pager/api/current.api
pager/src/main/java/com/google/accompanist/pager/Pager.kt

Rename defaultPagerFlingConfig to rememberPagerFlingConfig

---

pager/api/current.api
pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/main/java/com/google/accompanist/pager/PagerState.kt

[Pager] Add InteractionSource property

---

insets/api/current.api
insets/src/main/java/com/google/accompanist/insets/WindowInsets.kt

Expose display cutout insets as well as the raw window insets

---

insets/api/current.api
insets/src/main/java/com/google/accompanist/insets/Padding.kt
insets/src/sharedTest/kotlin/com/google/accompanist/insets/InsetsAssertions.kt

This will create a new easy to use modifier for the newly exposed Cutout Insets from #685.
Additionally I have added the cutouts to the existing test

Added cutout padding modifier

---

.github/workflows/build.yml
.github/workflows/device-tests.yml

Re-enable API 29 emulators

---

pager/src/main/java/com/google/accompanist/pager/PagerState.kt

targetPage was return currentPage even if currentPageOffset was negative

---

pager/src/main/java/com/google/accompanist/pager/SnappingFlingBehavior.kt

Removed any references to pages, etc.
Also fixed a bug where it would use a decay fling for velocities which would not reach the next item.

Tidy up SnappingFlingBehavior

---

gradle/libs.versions.toml

[Navigation] Update Navigation to 2.4.0-alpha10

---

docs/navigation-material.md
gradle/libs.versions.toml
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
sample/src/main/java/com/google/accompanist/sample/navigation/material/BottomSheetNavSample.kt

To be merged once Nav 2.4.0 Alpha 10 is released :)
Fixes #744

[Navigation Material] Update Docs and Sample to use new API for adding custom Navigators

---

gradle/libs.versions.toml
navigation-animation/api/current.api
navigation-animation/src/androidTest/java/com/google/accompanist/navigation/animation/NavHostControllerTest.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavHostController.kt

[Navigation Animation] Add ability to pass custom animators to rememberAnimatedNavController

---

pager/src/main/java/com/google/accompanist/pager/Pager.kt

[Pager] Allow HorizontalPager to wrap content height and VerticalPager to wrap content width

---

pager/src/main/java/com/google/accompanist/pager/Pager.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseHorizontalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/BaseVerticalPagerTest.kt
pager/src/sharedTest/kotlin/com/google/accompanist/pager/PagerTest.kt

Fixes #890
Fixes #895
Fixes #893
Fixes #885

Fix for Pager loosing its restored or initial current page

---

navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt

We should only allow a single instance of an entry in either of the
visible entry lists.
#872

Make visible entries a set

---

appcompat-theme/src/sharedTest/kotlin/com/google/accompanist/appcompattheme/FakeTests.kt
insets/src/sharedTest/kotlin/com/google/accompanist/insets/FakeTests.kt
insets/src/sharedTest/kotlin/com/google/accompanist/insets/WindowInsetsTest.kt
navigation-animation/src/androidTest/java/com/google/accompanist/navigation/animation/FakeTests.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/FakeTests.kt
pager-indicators/src/sharedTest/kotlin/com/google/accompanist/insets/FakeTests.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/FakeTests.kt
placeholder/src/sharedTest/kotlin/com/google/accompanist/placeholder/FakeTests.kt
swiperefresh/src/sharedTest/kotlin/com/google/accompanist/swiperefresh/FakeTests.kt
systemuicontroller/src/sharedTest/kotlin/com/google/accompanist/systemuicontroller/FakeTests.kt

As per comment on #822, this PR expands that fix to the whole project
https://developers.google.com/style/word-list?hl=en#dummy-variable

[All] Renaming sharding tests to more inclusive language

---

gradle/libs.versions.toml

Update to Snapper v0.1.2

---

appcompat-theme/build.gradle
drawablepainter/build.gradle
flowlayout/build.gradle
gradle.properties
gradle/libs.versions.toml
insets-ui/build.gradle
insets/build.gradle
internal-testutils/build.gradle
navigation-animation/build.gradle
navigation-material/build.gradle
pager-indicators/build.gradle
pager/build.gradle
permissions/build.gradle
placeholder-material/build.gradle
placeholder/build.gradle
sample/build.gradle
swiperefresh/build.gradle
systemuicontroller/build.gradle

Remove compose compiler version and match compose version

Update to Compose 1.1

---

docs/webview.md
web/README.md

[Web] Fix doc samples

---

sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerDifferentPaddingsSample.kt
sample/src/main/res/values/strings.xml

for the first/list item and the rest of the items
Fixes https://github.com/google/accompanist/issues/1033

[Pager] Add a demo for a pager with different paddings

---

README.md
insets/README.md

Moved to the bottom and marked as deprecated

[Insets] Update README to deprecate Insets

---

.github/ISSUE_TEMPLATE/navigation-animation-bug-report.md
.github/ISSUE_TEMPLATE/navigation-material-bug-report.md

This change gives us two separate templates for Material and Animation bugs so that Jeremy has to suffer less bc of Nav Material issues :)

Add issue template for Nav Material bugs

---

.allstar/binary_artifacts.yaml

Opt out of allstar

---

docs/navigation-animation.md

Suggesting some changes based on my initial readthrough of this doc.
* Move Download section to the top
* Add sentence to help guide the reader to the instructions for either implementing nav animation for the first time, or migrating to it.

[Docs] Update Navigation Animation docs

---

gradle/libs.versions.toml

Moving to the latest Navigation release

[Navigation Animation] Bump Navigation version to 2.5.0-rc02

---

gradle.properties
gradle/libs.versions.toml

Compose 1.2.0-rc01

---

pager-indicators/api/current.api
pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/pager/HorizontalPagerLoopingTabsSample.kt
sample/src/main/res/values/strings.xml

- I want to prevent the Tab Indicator from crashing in a loop as well as #1158 .
https://user-images.githubusercontent.com/13705006/174014528-207819e9-9865-469d-b458-3015cc7b7031.mp4

[pager-indicator] Support tab indicator of looping page with infinite page size

---

appcompat-theme/build.gradle
drawablepainter/build.gradle
flowlayout/build.gradle
gradle.properties
gradle/libs.versions.toml
insets-ui/build.gradle
insets/build.gradle
internal-testutils/build.gradle
navigation-animation/build.gradle
navigation-material/build.gradle
pager-indicators/build.gradle
pager/build.gradle
permissions/build.gradle
placeholder-material/build.gradle
placeholder/build.gradle
sample/build.gradle
swiperefresh/build.gradle
systemuicontroller/build.gradle
web/build.gradle

Compose 1.2.0-rc03

---

docs/systemuicontroller.md
sample/src/main/java/com/google/accompanist/sample/systemuicontroller/DocsSamples.kt

Found a minor typo in the docs+samples. 
setStatusBarsColor -> setStatusBarColor
setNavigationBarsColor-> setNavigationBarColor
Thanks!

[systemUiController] Minor typos in docs: setStatusBarColor, setNavigationBarColor

---

permissions/src/androidTest/java/com/google/accompanist/permissions/MultipleAndSinglePermissionsTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/MultiplePermissionsStateTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/PermissionStateTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/RequestMultiplePermissionsTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/RequestPermissionTest.kt
permissions/src/androidTest/java/com/google/accompanist/permissions/TestUtils.kt

[Permissions] Fix tests not working on new emulator targets

---

adaptive/src/main/java/com/google/accompanist/adaptive/TwoPane.kt

[Adaptive] Use early-return in placement

---

gradle/libs.versions.toml

Updates Android Gradle Plugin to stable 7.3.0

Update AGP to 7.3.0

---

.github/ISSUE_TEMPLATE/web-bug-report.md

[Meta] Add a web issue template

---

.github/workflows/build-snapshot.yml
.github/workflows/build.yml
.github/workflows/device-tests.yml

fix(ci): replace set-output to GITHUB_OUTPUT

---

docs/swiperefresh.md

added link to compose swipe refresh documentation

Updated swiperefresh.md

---

docs/appcompat-theme.md
docs/swiperefresh.md
docs/themeadapter-core.md

Some drive-by fixes for broken links and invalid formatting

[Docs] Fix multiple formatting errors

---

.idea/inspectionProfiles/ktlint.xml
.idea/kotlinc.xml
adaptive/build.gradle
flowlayout/src/sharedTest/kotlin/com/google/accompanist/flowlayout/LayoutTest.kt
gradle.properties
gradle/libs.versions.toml
insets/src/main/java/com/google/accompanist/insets/Padding.kt
insets/src/main/java/com/google/accompanist/insets/Size.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedComposeNavigator.kt
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/NavGraphBuilder.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt
navigation-material/src/main/java/com/google/accompanist/navigation/material/NavGraphBuilder.kt
pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt
placeholder-material/src/main/java/com/google/accompanist/placeholder/material/Placeholder.kt
placeholder-material3/src/main/java/com/google/accompanist/placeholder/material3/Placeholder.kt
placeholder/src/main/java/com/google/accompanist/placeholder/Placeholder.kt
sample/src/main/java/com/google/accompanist/sample/MainActivity.kt

Upgrade to Compose 1.4-alpha05

---

.idea/inspectionProfiles/ktlint.xml
.idea/kotlinc.xml
insets/src/main/java/com/google/accompanist/insets/Padding.kt
insets/src/main/java/com/google/accompanist/insets/Size.kt
pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt
placeholder-material/src/main/java/com/google/accompanist/placeholder/material/Placeholder.kt
placeholder-material3/src/main/java/com/google/accompanist/placeholder/material3/Placeholder.kt
placeholder/src/main/java/com/google/accompanist/placeholder/Placeholder.kt
sample/src/main/java/com/google/accompanist/sample/MainActivity.kt

Revert "Fix modifier lint warnings"

---

gradle.properties
gradle/libs.versions.toml

Release v0.31.1-alpha

---

README.md
flowlayout/README.md
flowlayout/src/main/java/com/google/accompanist/flowlayout/Flow.kt

Fix links to migration guide
Update Accompanist README.md

Deprecate FlowLayout: update migration links in Accompanist

---

.idea/kotlinc.xml
gradle.properties
gradle/libs.versions.toml
navigation-animation/src/main/java/com/google/accompanist/navigation/animation/AnimatedNavHost.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/BottomSheetNavigatorTest.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/NavGraphBuilderTest.kt
navigation-material/src/androidTest/java/com/google/accompanist/navigation.material/SheetContentHostTest.kt
pager-indicators/src/androidTest/kotlin/com/google/accompanist/pager/TabIndicatorWithFoundationPagerTest.kt

Fixes #1636 
Upgrades Compose to 1.5.0-beta01
Upgrades Kotlin to 1.8.21

Release v0.31.3-beta

---

gradle.properties
gradle/libs.versions.toml

Upgrade to Compose 1.5.0-beta02

Release 0.31.4-beta

---

gradle.properties
gradle/libs.versions.toml

Upgrade to Kotlin 1.8.22
cc #1487

Upgrade to Compose 1.5.0-beta03

---

gradle.properties
gradle/libs.versions.toml
navigation-material/api/current.api
navigation-material/src/main/java/com/google/accompanist/navigation/material/BottomSheetNavigator.kt

Fixes #1665
Fixes #1671 
Currently blocked by navigation material needing upgrades

Upgrade to Compose 1.6

---

adaptive/build.gradle.kts
gradle/libs.versions.toml
pager/build.gradle.kts
pager/src/main/java/com/google/accompanist/pager/PagerState.kt
permissions/build.gradle.kts
placeholder-material/build.gradle.kts
placeholder-material3/build.gradle.kts
placeholder/build.gradle.kts
testharness/build.gradle.kts

We shouldn't be adding this dependency as it then is imposed on apps that use Accompanist and it is basically unused anyway.

[All] Remove napier

---

docs/insets.md
pager/src/androidTest/kotlin/com/google/accompanist/pager/InstrumentedHorizontalPagerTest.kt

Replaces a couple instances of corp URLs with their publicly accessible versions.

[Docs] Replace corp URLs with publicly accessible ones

---

gradle.properties

Release the Compose 1.7 version

Release v0.35.0-alpha

---

docs/testharness.md

Small change to fix a typo in the testharness doc README.

Update testharness docs to fix warning note

---

pager-indicators/src/main/java/com/google/accompanist/pager/PagerTab.kt

Reverts google/accompanist#1755

Revert "[pager-indicators] Drop false-positive deprecation of pagerTabIndicatorOffset()"

---

docs/themeadapter-appcompat.md
docs/themeadapter-core.md
docs/themeadapter-material.md
docs/themeadapter-material3.md

docs: fix some comments

---

.github/workflows/build.yml
gradle.properties

Release 0.35.1-alpha

---

docs/navigation-material.md

See https://google.github.io/accompanist/navigation-material/

Fix markdown layout bug in navigation-material.md

---

build-logic/convention/src/main/kotlin/com/google/accompanist/KotlinAndroid.kt
sample/build.gradle.kts
sample/src/main/AndroidManifest.xml
sample/src/main/java/com/google/accompanist/sample/MainActivity.kt
sample/src/main/java/com/google/accompanist/sample/MainScreen.kt
sample/src/main/java/com/google/accompanist/sample/adaptive/DraggableFoldAwareColumnSample.kt

I will convert the actual samples to M3 in a followup PR

Convert sample app activity to Compose
